herbstluftwm/herbstluftwm

src/clientlist.cpp

Add missing window_title_changed hook.

---

src/clientlist.cpp

Changed XFetchName to XGetWMName as described in issue #64, first time contributing to any project and first time writing and not just reading C/C++ so please go ahead and reject / tell me if I did something wrong.

Changed XFetchName to XGetWMName, fixing issue #64

---

src/layout.h

Fix missing overrides

---

src/arglist.cpp
src/arglist.h
src/floating.cpp
src/mouse.cpp
src/mouse.h
src/rectangle.cpp
src/rootcommands.cpp
src/tagmanager.cpp
src/tmp.cpp
src/utils.cpp
src/utils.h

Make clear that this does not alter the object

Clarify method signature

---

src/attribute_.h
src/layout.cpp
src/layout.h
src/tag.cpp
src/tag.h
tests/test_layout.py
tests/test_tags.py
tox.ini

Re-implement tag attributes from master (frame_count, client_count, curframe_windex, curframe_wcount). This allows detailed testing of the tiling commands.

Add remaining tag attributes

---

tests/test_monitor.py

This also adds assertions for the focused monitor in the basic
monitor-related test cases.

Test effect of monitor focus on new clients

---

tests/conftest.py
tests/test_clients.py
tests/test_root_commands.py
tests/test_rules.py

Add tests for various types of completion functions.

Add some completion tests

---

.travis.yml

This makes it much easier to spot correlations between failing and
suceeeding tests.

Travis: Call pytest with -v

---

src/ewmh.cpp
src/mouse.cpp
src/mouse.h

For this, MouseBinding is turned from a struct into a class.

Store mouse binding command as vector of strings

---

www/compose.py

Also fix flake8 warnings while here

Update compose.py to Python 3

---

.codecov.yml

Adding this file to the master branch is an attempt at getting CodeCov
to actually interpret the file.

Add configuration file for CodeCov

---

src/clientmanager.cpp

Clean all Client objects on ClientManager shutdown

---

src/clientmanager.cpp
tests/conftest.py
tests/test_clients.py
tox.ini

This uses python-xlib in the tests.

Add tests for urgent windows

---

src/CMakeLists.txt
src/indexingobject.h
src/monitormanager.cpp
src/monitormanager.h
src/tagmanager.cpp
src/tagmanager.h

I always get confused when I see this class about what it does. Hope the proposed name is liked as well the old one.

Rename ChildByIndex to IndexingObject

---

ci-build.py

This removes the rather hard dependency on executing in a Docker
environment where the repository is mounted at /hlwm.
Beware that the script modifies the ccache configuration. Passing a
custom folder to --ccache is highly recommended.

ci-build.py: Do not assume /hlwm as repo root

---

src/monitormanager.cpp
src/plainstack.h
src/stack.cpp
src/stack.h

At the same time, call the member variable top_. This simplifies the
code in stack.cpp.

Use PlainStack in the Stack class

---

src/ewmh.cpp
src/xconnection.cpp
src/xconnection.h

Use this in Ewmh::isWindowStateSet() and in XConnection::windowPid().

Add wrapper around XGetWindowProperty()

---

doc/herbstluftwm.txt
src/command.cpp
src/main.cpp
src/monitor.cpp
src/monitordetection.cpp
src/monitordetection.h
src/x11-types.cpp
src/x11-types.h
winterbreeze.asciidoc

Implement detect_monitors --list-all, and make the output of
herbstluftwm --version.

Prepare detect monitors for multiple backends

---

src/CMakeLists.txt
src/client.cpp
src/client.h
src/clientmanager.cpp
src/decoration.cpp
src/decoration.h
src/floating.cpp
src/mouse.cpp
src/root.cpp
src/theme.cpp
src/theme.h

Move the Theme to an extra file theme.h/.cpp annd make the
Decoration-member of Client a pointer.

Resolve dependencies of and to Decoration

---

src/hookmanager.cpp
src/hookmanager.h
src/object.cpp
src/object.h

Remove functions for attribute (and action...) access that aren't used
and that will not be used in the future.

Remove unused functions of Object

---

src/keycombo.h
src/mouse.cpp
src/mouse.h
src/mousemanager.cpp

Introduce the class MouseCombo, inheriting from ModifierCombo, that
represents a combiniation of modifiers presses together with a mouse
button.

Introduce MouseCombo class for modifiers + button

---

src/globals.h
src/main.cpp

Also remove the leftover g_aboutToQuit from globals.h

Remove globals for screen size

---

src/client.cpp

It's writable in master and should indeed be writable.

Make the ewmhrequests attribute writable

---

NEWS
doc/herbstluftwm.txt
src/main.cpp
src/rootcommands.cpp
src/rootcommands.h
tests/test_root_commands.py

Add a new command 'export' which is a convenience wrapper around 'setenv'.

New command: export

---

src/xmainloop.cpp
tests/test_x11.py

This adapts ebed05c from master to winterbreeze (and slightly extends
it). This solves #576.

Position windows on configure requests monitor relative

---

CMakeLists.txt
share/CMakeLists.txt

Install the fish completion files to the appropriate directories.

Install fish completion

---

src/monitormanager.cpp
src/monitormanager.h
src/root.cpp
src/theme.cpp
src/theme.h

Add signals to automatically relayout all monitors whenever a theme attribute changes.

Relayout all monitors whenever the theme changes

---

tests/conftest.py

While https://github.com/python-xlib/python-xlib/pull/160 is not merged,
try to avoid issue #609 by attempting to open the display multiple times
as long as no TypeError occurs anymore.

Work around the TypeError in Xlib.display.Display()

---

src/layout.cpp
src/layout.h

Also inline smart_window_surroundings() since it is used only once.

Remove unnecessary functions in layout.h

---

src/mouse.h
src/mousemanager.cpp
src/mousemanager.h
src/xmainloop.cpp

Make the class MouseBinding and many member functions of MouseManager
private members of MouseManager.

Make MouseBinding private nested class

---

src/xconnection.cpp
src/xconnection.h
src/xmainloop.cpp

More verbose and human readable xerror output

---

src/clientmanager.cpp
src/stack.cpp
src/tag.cpp
src/tag.h
src/tagmanager.cpp
tests/test_stack.py

By this, also take care that the layers are correctly set, e.g. when a
new client is added to a floating tag.

Let HSTag take care of inserting new stack slices

---

ipc-client/main.c
tests/test_herbstclient.py

Also remove debug output from the argument parsing for '--count'.

Add tests for herbstclient

---

src/ewmh.cpp
src/ewmh.h
src/xconnection.cpp
src/xconnection.h

Read all the EWMH settings from the root and client windows on startup.

Read EWMH settings from previous WM on startup

---

src/main.cpp

Free XConnection in error case

---

tests/conftest.py
tests/test_ewmh.py

Add some tags and do a wmexec, to see if the tags are still there after
restart. (Also: this is the first test testing wmexec)

Test tag restore on wmexec

---

ci/Dockerfile.ci-disco
share/CMakeLists.txt
tests/test_herbstluftwm.py

We should test if the default autostart from share/ works by running it
with bash -e.

Add test for default autostart

---

src/utils.cpp
src/utils.h

Remove old utility functions that are no longer needed in the C++
codebase.

Remove unused c-style utility functions

---

tests/conftest.py
tests/test_floating.py

Add tests for moving a window in floating mode with the key bindings.

Add tests for directional window shift

---

src/completion.cpp

Add missing iostream include to completion.cpp

---

CMakeLists.txt

If you managed to install hlwm, you probably don't need this file in
your docs anymore...

Don't install INSTALL

---

ci/check-using-std.sh
src/arglist.cpp
src/client.cpp
src/command.cpp
src/framedata.cpp
src/frameparser.cpp
src/frametree.cpp
src/keycombo.cpp
src/monitor.cpp
src/mouse.cpp
src/mousedraghandler.cpp
src/regexstr.cpp
src/rootcommands.cpp
src/rules.cpp
src/stack.cpp
src/tag.cpp
src/tagmanager.cpp
src/types.cpp
src/x11-types.cpp
src/xconnection.cpp

The reporoot directory was not correctly set,
so CI build just complained about
grep: /hlwm/ci/src/*.cpp: No such file or directory
Fix this and all found occurrences.

Fix using std checker

---

src/frametree.cpp
src/regexstr.cpp
src/rules.cpp

Remove all 'using std::regex' in the cpp files.

Do not import std::regex into namespace

---

src/command.cpp
src/ewmh.cpp
src/frameparser.cpp
src/ipc-server.cpp
src/keycombo.cpp
src/main.cpp
src/monitor.cpp
src/mousemanager.cpp
src/namedhook.cpp
src/rectangle.cpp
src/tag.cpp

Remove unused using statements

---

src/byname.cpp
src/clientmanager.cpp
src/ewmh.cpp
src/frametree.cpp
src/hlwmcommon.cpp
src/ipc-server.cpp
src/keycombo.cpp
src/layout.cpp
src/monitormanager.cpp
src/object.cpp
src/rootcommands.cpp
src/settings.cpp
src/tag.cpp
src/tagmanager.cpp
src/xconnection.cpp

Use empty() for checking container size

---

src/frametree.cpp

Add more braces, missed a spot

---

src/attribute_.h
src/optional.h
src/signal.h
src/theme.h
src/types.h
src/utils.h

Forgot to add header-filter to the previous clang-tidy run...

Fix braces in header files, too

---

src/floating.cpp
src/x11-types.h

Move this out of the code for the directional shift such that we can
use the edge detection soon for directional resize in tiling mode.

Separate code for rectangle edge detection

---

.clang-tidy
src/types.cpp
src/types.h

Also rename the last mismatches

Add parameter definiton check to clang-tidy

---

src/client.cpp
src/client.h
src/layout.cpp
src/monitor.cpp
src/tilingresult.h
tests/test_layout.py

In the TilingResult, explicitly mention which clients should have a
minimal decoration, and later pass that to Client::resize_tiling().
This solves #803.

Activate smart_window_surroundings again

---

src/tag.cpp
tests/test_tags.py

This fixes issue #830 thanks to @tiosgz for spotting this!

Count floating clients in tags.*.client_count

---

NEWS
doc/herbstluftwm.txt
src/panelmanager.cpp
src/panelmanager.h
src/root.cpp
src/settings.cpp
src/settings.h

This helps working around other problems with panels, such as the one in
issue #815.

New setting 'auto_detect_panels'

---

share/autostart

Also update a few comments in the autostart.

Set the resizestep in the autostart to 0.02

---

tests/test_mousebind.py

This implicitly adds a test for update_dragged_clients.

Make live update configurable in resize test

---

src/ewmh.cpp
tests/conftest.py

This is sensible for debugging and in the CI, and it improves the code
coverage }:->

Print initial EWMH state in verbose mode

---

tests/test_layout.py

This requires the return code fix of PR #885 to succeed.

Test 'focus_edge' command

---

tests/test_rules.py

Add test for switchtag

---

INSTALL
MIGRATION

It seems that github now respects them for rendering the files online.

Mention asciidoc filetype in vim modelines

---

release.sh

Fix typos and remove an unused statement

Minor changes to release.sh

---

ci/Dockerfile.ci-focal
ci/Dockerfile.ci-trusty

Remove some unused packages and an outdated comment

CI: Remove some unused packages from Dockerfile

---

tests/test_herbstclient.py

There is a race-condition in both test cases for herbstclient --wait
that comes from the fact that we don't know how fast herbstclient
connects to hlwm and starts listening for hooks. In this commit, we
simply hope that `hc --wait` boots up within the time needed for two `hc
true` calls.
This issue only exists for --wait and not for --idle, because for
--wait, we need to test that herbstclient indeed exits after a fixed
number of hooks (--count).
For hc --idle, this issue does not appear in the HcIdle class in
conftest.py, because there, we can wait for hc --idle to boot up by
calling 'emit_hook' multiple times (hence, this is not applicable for
synchronizing the bootup of --wait).
I assume that this fixed the issue #954 of the erroring testsuite (at
least it tackles the backtraces …

Quickfix race-condition in hc --wait testcases

---

src/floating.h

Remove the old declarations for the init and destroy functions of the
'floating' module.

Remove old function declarations

---

NEWS

Some entries were actually bug fixes and one fix is rather a feature

Reorder some NEWS entries

---

tests/test_rules.py

This adds a test case where list_rules prints a rule involving negation.

Add test list_rules printing 'not'

---

doc/herbstluftwm.txt

Fix manpage for foreach command

---

LICENSE
doc/herbstclient.txt
doc/herbstluftwm.txt
ipc-client/main.c
src/desktopwindow.h
src/main.cpp

In the cpp source files, I removed the copyright altogether, since we
have the LICENSE file.
This fixes #1000.

Update copyright years

---

doc/herbstluftwm.txt
src/client.cpp
tests/test_hook.py

Emit the "fullscreen" hook again

---

ci/diff-json-doc.py

Various improvements:
- Always fetch 'github/master'
- Make the 'oldref' argument optional
- Automatically derive where to put the comment from 'newref'

Improvements in diff-json-doc.py

---

tests/test_rules.py

Add tests that ensure that minimized clients stay invisible, even if
apply_rules brings them from an invisible to a visible tag.
This fixes #1040.

Test apply_rules for minimized clients

---

ci/Dockerfile.ci-focal
ci/Dockerfile.ci-trusty

We will need them for xft support.

Install xft and freetype in docker images

---

.github/workflows/hlwm.yml
ci/build.py

This should prevent issues like #1093

Test install target in CI run

---

ipc-client/ipc-client.c
ipc-client/ipc-client.h

Doesn't seem to be used anywhere.

Remove unused hc_send_command_once

---

src/watchers.cpp
src/watchers.h
tests/test_meta_commands.py

Remove (currently?) unused vector, fix whitespace
and add a test for missing arguments.

Fix minor things in watcher code

---

share/autostart

Solve #1133 by offering an un-minimize shortcut in the default autostart.

Add a default unminimize shortcut

---

tests/test_tags.py

Fix some low hanging fruit. There is more in there.

Extend tag manager test suite

---

src/monitormanager.h

The function list_padding is declared in MonitorManager but not defined.
It is however defined in Monitor.

Remove undefined function

---

src/arglist.cpp
src/arglist.h
src/attribute.h

The code coverage showed that these are not used.

Remove unused functions from ArgList and Attribute

---

tests/test_herbstluftwm.py

This adds tests for herbstluftwm's command line flags for help and
version.

Test herbstluftwm version and help flags

---

tests/conftest.py

In order to be able to use the X11 class separately, move the code for
it (and for the display connection) out of the fixtures x11 and
x11_connection.
This only moves lines and changes their indentation.

Move x11 connection out of fixtures

---

tests/test_monitor.py

Add test cases for various commands on monitors and for the setting
hide_covered_windows.

Test cases for monitor.cpp

---

src/typesdoc.cpp
src/typesdoc.h

Just a straightforward description of the WxH+X+Y syntax.

Add types doc for the 'rectangle' type

---

src/command.cpp
src/main.cpp
src/monitor.h
src/monitormanager.cpp
src/monitormanager.h
tests/test_monitor.py

This migrates the 'add_monitor' command to ArgParse, and now also
verifies that the given rectangle has at least the minimum window size.

Migrate 'add_monitor' to ArgParse

---

src/client.cpp
src/client.h

client: Remove unused methods

---

tests/test_ewmh.py

This adds tests for the EWMH client message handling for closing windows
and for starting/stopping mouse dragging operations.

Test EWMH client messages

---

ci/build.py

Let's see which test takes the longest...

CI: Display the top 10 slowest tests

---

www/contrib.txt

Also avoid some exclamation marks.

Fix typo in contrib.txt

---

src/decoration.cpp

If inner_width, outer_width, and border_width are identical, then this
makes one of the rectangle heights negative. Since heights of XRectangle
are of type unsigned short, this caused a very large rectangle. To fix
this, the helper function toUnsigned() now correctly casts widths and
heights to unsigned short.
This fixes #1418

Clamp to XRectangle dimensions

---

NEWS
scripts/q3terminal.sh
scripts/scratchpad.sh
src/indexingobject.h
src/tag.cpp
src/tag.h
src/tagmanager.cpp
src/tagmanager.h
tests/test_tags.py

This adds a new attribute that keeps tags near the end of the tag list.

Add 'at_end' attribute for tag order

---

src/CMakeLists.txt
src/layout.cpp
src/layout.h
src/layoutalgoimpl.cpp
src/layoutalgoimpl.h

This change encapsulates the layout algorithms in their own module. The first benefit is that the long layout.cpp becomes shorter. The other benefit is that it will be easier to implement new layout algorithms (which is requested quite frequently).

Move layout algorithms to own module

---

doc/herbstluftwm.txt

Thanks to @yushyin for reporting this!

Fix 'latest-minimized' -> 'last-minimized' in doc

---

src/css.cpp
src/css.h
src/hlwmcommon.cpp
src/keymanager.h
src/layout.h
src/mousedraghandler.h
src/rules.cpp
src/theme.cpp
src/widget.cpp

Remove some of the includes as suggested by iwyu

Remove some includes

---

MIGRATION
NEWS
src/layout.cpp
src/settings.cpp
src/settings.h
tests/test_doc.py

Similarly to the changes in `smart_frame_surroundings`, this change makes
`smart_window_surroundings` more fine-grain.
This closes #1530

Expand 'smart_window_surroundings' functionality
