herbstluftwm/herbstluftwm

- config.mk
Allows the location of the pkg-config binary to be set as a variable
during make. This is needed to use prefixed pkg-config for cross
compilation.
Submitted with the permission of the original author (see comments in https://galileo.mailstation.de/gerrit/#/c/1249/).
> Use PKG_CONFIG variable during make.

- CMakeLists.txt
- HACKING
- single file.
- supports out of source builds. (no files made in source dir)
builds binary, docs, installs.
For build output see: http://members.iinet.net.au/~ideasman42/herbstluftwm_cmake.html
Advantages with CMake are:
- loads as a project file in various IDE's.
- support multiple build-dirs (release & debug for eg).
- easier editing/configuring of build options, compilers... etc.
- improved portability (between different compilers and platforms).
> Add initial support for CMake

- src/monitor.cpp
When `use`ing a tag that was already shown on another monitor and
swap_monitors_to_get_tag was set, we did not save the current tag in
monitor->previous_tag which resulted in use_previous not jumping back to
the previous tag but the one before that.
> Save previous tag when stealing from other monitor

- share/panel.sh
panel.sh used a mix of `"${herbstclient_command[@]}"` and `herbstclient`. Also, if herbstclient_command was set and was an array, unquoted use would not work with dzen's `^ca()`.
I have tested it by setting `herbstclient_command=( bash -c 'exec herbstclient "$@"' arg0 )` just before `HC_QUOTED`.
> Cleanups for panel.sh

- doc/herbstluftwm-tutorial.txt
> Typo in herbstluftwm-tutorial

- www/download.txt
This adds a link to the package of `herbstluftwm` for opensuse to the download page of the website.
https://software.opensuse.org/package/herbstluftwm
> opensuse package available

- src/clientlist.cpp
If you have a hlwm monitor with an y-offset, the position of floating windows was calculated wrong. This also affected mouse resize behavior.
> Fix typo for client position in floating mode

- src/mouse.cpp
rect = &frame->last_rect is absolute, so there's no need to convert g_button_drag_start.
Fixes #87.
> Fix mouse resize in tiled mode for multi-monitor

- src/xconnection.cpp
This can be triggered by not having a DISPLAY environment variable set.
> Add error handling for XOpenDisplay()

- .travis.yml
This introduces a matrix of builds using combinations of Ubuntu versions and compilers (and their versions).
Additionally, one of the matrix entries is used to run tox instead of the usual build-install-execute script.
> Rework .travis.yml: Build matrix, integrate tox

- src/layout.cpp
This change is motivated by a compiler warning for the implicit
fallthrough in the switch/case block.
Extracting the special "@" case simplifies the remaining logic, making
it easier to follow, and also solving the warning along the way.
> Rewrite HSFrameSplit::lookup()

- src/main.cpp
- src/utils.cpp
- src/utils.h
- src/xconnection.cpp
The current implementation of die() triggers a compiler warning
about the format string not being a literal.
Most of its points of usage are not really needed (malloc never fails[tm]),
or can be replaced with cerr/exit.
> Remove die() from utils

- ipc-client/client-utils.c
- ipc-client/client-utils.h
- ipc-client/ipc-client.c
- ipc-client/ipc-client.h
- ipc-client/main.c
This PR cleans up the ipc-client subdirectory aka herbstclient.
@dnnr: Can you take a look at it? I'm unsure about the changes in the Makefile and the config.mk. It's better than before, but I'm not very familiar how to properly setup the dependencies between the Makefile variables.
> Drop glib.h from ipc-client and further clean ups

- .travis.yml
Wait for hlwm to shut down in travis in order to avoid the fatal IO error message complaining about the lost display.
> Gently shut down hlwm in travis

- config.mk
There are no warnings for this in the codebase.
> Remove obsolete suppression for -Winvalid-offsetof

- config.mk
Using g++ circumvents explicit compiler selection via the CXX
environment variable. Using $(CXX) as fallback ensures that the selected
compiler is used for linking.
> Use $(CXX) as a default value for LDXX

- src/layout.cpp
Comparison with size_t caused zero to wrap to last
> Fix error clamping first client when unmapping

- src/arglist.cpp
- src/arglist.h
- src/attribute.h
- src/attribute_.h
- src/clientmanager.h
- src/floating.cpp
- src/floating.h
- src/hook.h
- src/layout.cpp
- src/layout.h
- src/monitormanager.cpp
- src/monitormanager.h
- src/rootcommands.cpp
- src/types.h
- src/x11-types.cpp
- src/x11-types.h
This is a follow-up to the discussion in #152.
Ideas behind this approach:
- Strip logic of type conversions out of Attributes, put it into types.h instead
- Have a common interface for said conversions such as the types we have conversions for can be easily made into attributes (e.g. Rectangle, which can be used to have the geometry of a client as attr)
- Converting to/from user is always done in a consistent manner (parsing throws std::exceptions)
- Conversions are defined where the types are defined, e.g. Color conversions are defined in x11-types.h where Color is defined
Open issue: Color constructor that takes a string currently fails silently (as it did previously) and falls back to black. I would suggest to let the exception fall through instead.
> Common interface and behavior for communicating basic types with the user

- tests/test_stack.py
In addition to some (mostly cosmetic) cleanup, this also verifies the
stack more strictly, which confirms the absence of a subtle,
almost-merged mistake in slice_create_frame().
> Clean up and extend test cases for stack

- src/attribute_.h
- src/monitor.cpp
- src/monitor.h
- src/tag.cpp
- src/tag.h
This new approach makes the signature for Attribute_ and DynAttribute_ very uniform. HSTag and HSMonitor are already adapted to the new framework. Other classes still use the old constructors that are kept for the time being for compatibility reasons.
> Pass Attribute owner directly to constructor

- src/rules.cpp
- src/rules.h
- src/utils.cpp
- src/utils.h
- tests/test_rules.py
Along with this change, the consequence value is already turned
into an std::string, eliminating all GLib usage around consequences.
> Manage rule consequences as vector of non-pointers

- .travis.yml
The "python" key is only meaningful if the selected language is
"python". Selecting "cpp" is of not much use to us since we explicitly
install a specific version anyway.
Because Python 3.7 is not available on 14.04, the version spec is moved
into the xenial-based job that executes the tests. Other jobs do not
care about Python.
> Fix python version selection in Travis

- src/arglist.cpp
- src/arglist.h
- src/clientmanager.cpp
- src/command.cpp
- src/command.h
- src/main.cpp
- src/monitor.cpp
- src/monitormanager.cpp
- src/rectangle.cpp
- src/rootcommands.cpp
- src/rootcommands.h
- src/settings.cpp
- src/tagmanager.cpp
- src/tmp.cpp
- src/types.cpp
- src/types.h
- tests/test_root_commands.py
Input is an ArgList that also stores the name of the command that
was called. It can only be constructed from a command name and (optionally) a
list of arguments to prevent wrong use.
All accessors from ArgList can be used. operator>> is overridden to
return the correct reference.
>  Cleanup interface of Input

- .travis.yml
- tests/conftest.py
- tox.ini
This removes the python version selection from .travis.yml because
it doesn't work as expected, so no f-strings for us.
> Improve herbstclient output passthrough in tests

- src/decoration.cpp
Since client->dec is always be identical to "this", the local copy is
pointless.
> Remove redundant local in Decoration::redrawPixmap

- src/command.cpp
These arrays are iterated based on their sizeof(), so this kind of
zero-termination is not necessary.
> Drop unnecessary zero entries in array inits

- CMakeLists.txt
- src/mouse.cpp
- src/stack.cpp
This fixes two occurrences of a missing-field-initializers warning,
which is part of -Wextra.
A suppression unused-parameter is added because it is part of -Wextra
but triggers a lot of false positives (in the sense that those are no
bugs).
> Add -Wextra to debug build flags

- .travis.yml
- CMakeLists.txt
One of our flags is not compatible with clang. Adding it conditionally
fixes the Debug build when using clang.
In future steps, we can make use of warnings/checks that are only
available in clang.
> Make Debug build with with clang

- CMakeLists.txt
This is mostly restructuring, but also adds the following flags:
-Wshadow, -Wshadow-all, -Wduplicated-cond, -Wduplicated-branches,
-Wlogical-op, -Wuseless-cast
...and removes a suppression for shadow warnings in ctors.
> Explain our compiler flags, add more warnings

- src/rulemanager.cpp
- src/rulemanager.h
This more accurately reflects what the method does (i.e., not only
remove the first match).
> Rename RuleManager::removeRule() to removeRules()

- src/arglist.cpp
- src/clientmanager.cpp
- src/floating.cpp
- src/framedecoration.cpp
- src/layout.cpp
- src/monitor.cpp
- src/monitormanager.cpp
- src/object.cpp
- src/rootcommands.cpp
- src/settings.cpp
- src/tag.cpp
- src/tagmanager.cpp
- src/tilingresult.cpp
- src/tmp.cpp
- src/utils.cpp
In some cases, for rarely used symbols, "std::" is added to the
point-of-use.
In every other case, a "using std::…" statement is added.
For consistency, any existing "std::" prefixes are removed if they're
not necessary thanks to a corresponding "using" statement.
> Drop discouraged "using namespace std;"

- .travis.yml
Apparently, a recent change on Travis' side means that /etc/init.d/xvfb
does not exist on 16.04 anymore. Using the "services" approach is a
viable workaround on 16.04 but does not work on 14.04.
Abandoning the common script definition (which was only used by 2 of 4
jobs anyway) allows us to solve this as needed on the individual machine
types.
> Travis: Use xvfb differently on 16.04 and 14.04

- src/key.cpp
- src/key.h
This purposely leaves the C-style nature of KeyBinding (not being a
class, etc.) untouched in order to tackle that part separately.
> Turn g_key_binds from GList into std::vector

- src/key.cpp
- src/key.h
- tests/test_keybind.py
For this, the global g_key_binds is turned into a vector of unique_ptrs
to KeyBinding.
In future work, most of the standalone functions may be turned into
methods of KeyBinding.
This also extends the keybinding test suite a bit.
> Make KeyBinding a class, use Input for keybind cmd

- src/root.cpp
- src/root.h
This introduces an alphabetical ordering where possible, and extracts
special cases (having dependencies) into a separate block.
> Clean up initialization order for manager objects

- src/keymanager.cpp
We should not deny the setup of a new keybinding only because the KeySym
is unknown at the time of setup. Instead, unknown KeySyms are skipped
whenever (re)grabbing them.
> Do not deny key bindings for unknown symbols

- src/client.cpp
- src/key.cpp
- src/key.h
The tag was not used at all, and instead of the entire client, only the
keymask itself is relevant.
> Simplify signature for key_set_keymask()

- tests/conftest.py
- tests/test_stack.py
Instead of running "true" in an xterm with -hold, we now run "sleep
infinity". This allows the custom command to decide when the client
terminates.
> Tests: Offer custom command param in create_client

- src/client.cpp
- src/key.cpp
- src/key.h
- tests/conftest.py
- tests/test_clients.py
- tests/test_keybind.py
This implicitly fixes a memory leak in the old regex code (missing
regfree).
The new test is prepared to cover multiple scenarios, only one of which
works in current keymask implementation.
> Use std::regex for keymask, add tests

- src/CMakeLists.txt
- src/key.cpp
- src/key.h
- src/keycombo.cpp
- src/keycombo.h
- src/keymanager.cpp
- src/keymanager.h
- src/mouse.cpp
- tests/test_keybind.py
This encapsulates most stringification/parsing code for key combinations
into the KeyCombo class.
The keybinding_to_string() function remains for now, as it is still
needed for the completion code.
> Extract functionality into KeyCombo class

- src/keycombo.cpp
- src/keycombo.h
- src/mouse.cpp
Dealing with the structure of a KeyCombo (i.e., last token is keysym,
others are modifiers) is now part of fromString(). This makes the
renamed helpers for parsing modifiers and keysyms more flexible for
other use cases (completion in particular).
The helper for splitting a string into tokens is made public for future
use in completion code in KeyManager.
As a small cleanup, a local variable in mouse.cpp is renamed from
"string" to "str" to avoid shadowing the type.
> Clean up responsibilities of KeyCombo helpers

- .travis.yml
- ci-check-using-std.sh
This only enforces it for string (for now), to allow a gradual transition.
> Add CI check to enforce "using std::..." style

- src/command.cpp
- src/completion.cpp
- src/monitor.cpp
- src/namedhook.cpp
- src/rulemanager.cpp
- src/tag.cpp
- src/types.cpp
These were missed due to a mistake in the regexp used in the CI check
for std:: prefixes (will be fixed separately).
> Fix missed occurrences of std::string

- ci-check-using-std.sh
- src/arglist.cpp
- src/frametree.cpp
- src/hookmanager.cpp
- src/main.cpp
- src/namedhook.cpp
- src/object.cpp
- src/root.cpp
- src/rootcommands.cpp
Along the way, turn the CI check blacklist into a whitelist of remaining
symbols.
> Remove std:: prefixes for smart pointer symbols

- CMakeLists.txt
The DESCRIPTION argument is not understood by CMake 3.5, which satisfies
our version requirements and is the most recent version available on
Ubuntu trusty.
> CMake: Drop DESCRIPTION argument from project()

- .travis.yml
- ci-build.py
This change is a preparation for adding --coverage to the Debug flags.
It is necessary because ccache does not handle random cwds well in
conjunction with --coverage (known issue:
https://github.com/ccache/ccache/issues/268)
> Do not use random build directory in ci-build.py

- tests/test_keybind.py
Along the way, those three similar test cases are merged into a single
implementation.
> Add test for binding empty key sym

- .hlwm.imp
- ci-build.py
This adds our first useful mapping: Stopping IWYU from telling us to
include <bits/getopt_core.h> when <getopt.h> is the prescribed public
header.
> Introduce IWYU mapping file

- src/CMakeLists.txt
- src/childbyindex.cpp
For unclear reasons, this file made IWYU suggest that childbyindex.h
needed to include signal.h.
> Remove empty childbyindex.cpp (fix IWYU complaint)

- .mergify.yml
Apparently, Mergify is fixated on the configuration file as it is in the
default branch, regardless of a PR's base branch. So without this,
Mergify will waits for status-sucess=WIP in PRs made against
winterbreeze.
> Remove status-success=WIP from .mergify.yml

- tests/conftest.py
- tests/test_stack.py
We use 'read -n 1' in the test cases, which is a bash specific option.
To let the test cases run if bash is not the default shell, explicitly
use bash.
> Explicitly use bash in tests for read -n

- src/rectangle.cpp
- src/x11-types.cpp
- src/x11-types.h
This drops the glib dependency in rectangle.cpp. The new algorithm is
much different than the original code, but makes the whole algorithm
simpler, shorter, and hopefully much easier to read.
> Drop glib from the disjoin_rects algorithm

- src/clientmanager.h
- src/keymanager.cpp
In clientmanager.h, only a fwd decl of HSTag is required, instead of a
full include of client.h.
Removing the include uncovers a missing include of client.h in
keymanager.cpp, which is added.
> ClientManager: Use fwd decl of HSTag, drop include

- src/rulemanager.cpp
There is no C-style string handling in this file anymore, but
std::string is used.
> rulemanager.cpp: Use <string> instead of <cstring>

- src/main.cpp
- src/x11-types.cpp
- src/x11-types.h
Removing these reveals that main.cpp is missing an include of
<iostream>, which is added.
> x11-types.cpp: Drop unused <cstdio> and <iostream>

- src/floating.cpp
- src/layout.cpp
- src/layout.h
- src/tag.h
- src/x11-types.cpp
Removing these reveals that floating.cpp is missing an include of
<climits>, which is added.
> Drop some unused #include "glib-backports.h"

- tests/conftest.py
Turns out that just running "pytest" in the repository root happily
starts the tests, which kills all your existing windows.
To mitigate this, this adds a sanity check for $DISPLAY and changes
the startup order so that hlwm *should* refuse to launch due to the
already-running WM.
> Add mitigations against killing all clients on :0

- ci-build.py
Sometimes (but apparently not always), the pytest cache location happens
to be subdirectory of .tox/. To ensure that the pytest cache is not
persisted across builds (as .tox/ is) we always pass --cache-clear to
pytest.
> ci-build.py: Always clear pytest cache

- .travis.yml
Because we delete our .git at the beginning of our tests, the CodeCov
integration script has trouble finding our configuration file. Passing
it explicitly should fix this.
> Explicitly tell CodeCov about our .codecov.yml

- src/stack.h
<memory> (things like shared_ptr) is not used, but <set> is.
> Fix includes in stack.h (drop memory, add set)

- .codecov.yml
This is a rather new feature, but not yet very helpful because of our
known issues with flaky coverage.
> CodeCov: Disable PR status checks for now

- ci-build.py
Filter the output of fix_include by removing messages
of the pattern:
>>> Fixing #includes in 'somefilename.cpp'
No changes in file somefilename.cpp
This uses subprocess.run because the documentation of subprocess.check_call
says that it should not be combined with piped stdout (stdout=subprocess.PIPE).
> Avoid iwyu fix_include output for unchanged files

- src/rootcommands.cpp
- tests/test_root_commands.py
Writing a read-only attribute via set_attr led to a crash because
the wrong variable is used when creating the error message.
> Use right value for error message in set_attr

- src/client.cpp
- src/client.h
Also, group attributes together (even though some of them are not
attributes in winterbreeze yet, but only in master)
> Avoid wireAttributes() in Client

- tests/conftest.py
- tests/test_root_commands.py
In call_xfail_no_output(), assert that the command has indeed no
output. I think the former reading of the command name was "make
no assertion about the output".
> Let call_xfail_no_output() assert no output

- src/frametree.cpp
- src/layout.cpp
- src/layout.h
This also drops ALIGN_EXPLODE in favor of a temporary variable in the
split command handler.
> Replace plain enum with SplitAlign enum class

- src/entity.h
This eliminates the casts of enums to integers by using enum values as
keys in the map.
The relationship between the enum and the lists strings/chars also
becomes more explicit this way.
> More explicit mapping for entity type to str/char

- src/monitormanager.cpp
- tests/test_monitor.py
Monitor names are optional and a monitor with no name has the name
attribute empty. Only for add_monitor, it is not permitted to pass an
empty monitor name.
This is the current behaviour in master.
> Allow the monitor name to be empty

- .mergify.yml
On travis-ci.com, the PR status check appears to have a different "name"
than on travis-ci.org. Changing it like this might help.
> Update Mergify config to work with travis-ci.com

- src/client.cpp
- src/hook.cpp
- src/hook.h
- src/tag.cpp
- src/tagmanager.cpp
Passing multiple parameters via a vector/initializer list is shorter,
more type safe, and makes it easier to pass std::string.
> Remove hook_emit_list

- src/ewmh.cpp
- src/xconnection.cpp
- src/xconnection.h
Add a convenience wrapper XConnection::setPropertyCardinal() that takes
a vector of longs.
> Wrapper for XChangeProperty for type = XA_CARDINAL

- src/ewmh.cpp
- src/xconnection.cpp
- src/xconnection.h
Add a convenience wrapper XConnection::setPropertyWindow() that takes
a vector of Windows.
> Wrapper for XChangeProperty for type = XA_WINDOW

- src/ewmh.cpp
- src/ewmh.h
- src/ipc-server.cpp
- src/xconnection.cpp
- src/xconnection.h
Add a convenience wrapper XConnection::setPropertyString() that takes
a string or a vector of strings and sets the given property accordingly.
> Wrapper for XChangeProperty/XSetTextProperty

- src/ipc-server.cpp
- src/ipc-server.h
- src/main.cpp
Make the interface of the IpcServer the precise counterpart of
ipc-client.h. This is also removes IpcServer's dependency on command.h.
Now, the IpcServer calls a callback for each request received from a
(herbst-)client. The result of the callback is then sent back to the
(herbst-)client.
Formerly, the IpcServer called a function from command.h directly. Now, the
only in-project dependencies of IpcServer are ipc-protocol.h and xconnection.h.
> Make IpcServer the counterpart of ipc-client.h

- src/command.cpp
- src/command.h
- src/main.cpp
- src/monitormanager.cpp
- src/monitormanager.h
- src/stack.cpp
- src/stack.h
- tests/test_completion.py
Also provide another constructor to CommandBinding for commands
that sit in objects and that don't need an Input parameter.
> Move stack command to MonitorManager

- src/frametree.cpp
- src/layout.cpp
- src/layout.h
- src/main.cpp
- src/monitor.cpp
- src/tagmanager.cpp
- tests/test_x11.py
The focus setting helper frame_focus_recursive() was called in many
places (and the focus was still broken when the first client showed up).
However, every such call is followed by a call to Monitor::applyLayout()
which sets the object link clients.focus. If the window is not visible
yet, XSetInputFocus() has no effect. So we need to reset the focus on
MapNotify events.
Hence, we now directly set the keyboard focus at this single place in
Monitor::applyLayout().
> Fix keyboard focus

- tests/test_clients.py
Clean up test_fullscreen_ewmhnotify by defining a helper function for
setting an boolean attribute on the window of interest.
This also uses the fullscreen attribute instead of the fullscreen
command to make it also work we run this test case with other client
windows present.
> Use helper function in ewmhnotify test case

- src/indexingobject.h
- tests/test_monitor.py
- tests/test_tags.py
After removing indexed objects like monitors or tags, update the index
of the remaining objects.
This fixes #482.
This also makes some cosmetic changes in addIndexed().
> Update child indices after removal

- ipc-client/ipc-client.c
- ipc-client/ipc-client.h
- ipc-client/main.c
- tests/conftest.py
- tests/test_herbstclient.py
Before sending commands or listening for hooks, check that herbstluftwm
is running. This is done by reading the window id of herbstluftwm's hook
window and then checking that this window still exists.
In the test suite, it is checked that herbstclient recognizes an absent
herbstluftwm. Previously, sending commands without herbstluftwm made
herbstclient hang.
In this new test case, we either don't start hlwm or we make it quit
abnormally, so we don't want the hlwm_process fixture to start and check
that hlwm shuts down gently. Hence, this removes the autouse-flag from
the hlwm_process fixture. This does not affect the other taste cases,
because they actively rely on hlwm which depends on hlwm_process.
> Check in herbstclient if herbstluftwm is running

- cmake/debugflags.cmake
When running cmake mit -DCMAKE_BUILD_TYPE=Debug the option -Og sometimes
optimizes parameters away. For better debugging, let us switch to -O1
which should keep the variables intact.
> Use -O1 in CXXFLAGS in Debug build type

- src/clientmanager.cpp
- src/main.cpp
- src/monitor.cpp
- src/settings.cpp
- src/tagmanager.cpp
This fixes the crash when non-integer values are passed as the
respective arguments.
> Catch exceptions by stoi() and stoul() calls

- src/ewmh.cpp
- src/main.cpp
Whenever we have a Root-pointer present, we can use the ClientManager to
resolve X Window IDs to Client-pointers.
> Avoid get_client_from_window()

- ipc-client/main.c
Before each 'return EXIT_FAILURE' in main_hook() and main(), deallocate
the data allocated so far.
> ipc-client: Deallocate data in the case of errors

- src/main.cpp
- src/monitor.cpp
- src/monitordetection.cpp
- src/monitordetection.h
The interface for the monitor detection can be used in the version
command in order to print information about the features compiled into
herbstluftwm.
> Add an interface for monitor detection methods

- src/theme.cpp
- src/theme.h
- tests/test_theme.py
When re-setting a meta-attribute in the theme (e.g. theme.border_width),
propagate the value write to other attributes even if the value did not
change (e.g. theme.tiling.active.border_width was formely not updated
correctly).
> Bugfix in theme: propagate value write on same value

- src/ewmh.cpp
- src/ewmh.h
Pagers wanting to close a window send a _NET_CLOSE_WINDOW client message
to the root window, and this must be handled by the window
manager.
This adapts 0fdac2411db5f81e5d31515505aad00f17e6def7 to the winterbreeze
branch.
> Close window on _NET_CLOSE_WINDOW

- src/root.cpp
- src/tagmanager.cpp
- src/tagmanager.h
When removing a tag, update the ewmh desktop field for each client
because the indices have changed.
> Update all clients' ewmh desktop after tag removal

- src/CMakeLists.txt
- src/client.h
- src/desktopwindow.cpp
- src/desktopwindow.h
- src/ewmh.cpp
- src/ewmh.h
- src/main.cpp
- src/rules.cpp
Remember which desktop windows (xfdesktop) we have and force them to
stay below the other windows.
This is an adaption of 184f4b03a8f27563acadd07e0d5421018fe4da08 to the
new code base.
> Explicitly manage desktop windows

- src/client.cpp
- src/ewmh.cpp
- src/ewmh.h
- src/xconnection.cpp
This makes the window title getting work for utf8- and non-utf8-strings.
In XConnection::getWindowProperty(), convert an iso-encoded XA_STRING to
utf8.
This fixes #522.
> Use XGetProperty instead of XFetchName

- src/monitor.cpp
- tests/test_monitor.py
The tests will fail until the `tag_previous` pointers are updated correctly.
> Add tests for use_previous and focus stealing

- src/keymanager.cpp
- src/keymanager.h
- src/xkeygrabber.cpp
- src/xkeygrabber.h
- src/xmainloop.cpp
- src/xmainloop.h
Formerly, every event handler blindly casted the event to the expected
to the "right" event type by accessing the corresponding union member.
The current approach is as (un)safe, but it is less work in the event
handler.
> Cast to current xevent type during event handler call

- src/keycombo.cpp
- tests/test_keybind.py
- tests/test_mousebind.py
Use ArgList::split() to split a key combo into tokens, since this
handles a trailing delemiter correctly. E.g. "Mod1+Mod4+" splits
correctly to ["Mod1", "Mod4", ""]. This fixes the keybind and mousebind
completion for e.g. "Mod1+" and "Mod1+Mod4+".
> Fix key combo tokenizing with trailing delemiter

- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/framedecoration.cpp
- src/globals.h
- src/main.cpp
Remove the expensive and actually unneeded window_set_visible() and do
XMapWindow() and XUnmapWindow() where we actually need it. Note that
window_set_visible() was so complex because it has been used for
clients, formerly.
This allows us to inline the definitions of ROOT_EVENT_MASK and
CLIENT_EVENT_MASK.
> Remove window_set_visible(), inline event masks

- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/clientmanager.h
- src/indexingobject.h
- src/monitormanager.cpp
- src/monitormanager.h
- src/mousemanager.cpp
- src/mousemanager.h
- src/root.cpp
Explicitly maintain a drag mode in the MouseManager and maintain a
clients.dragged state (as in master) that points to the currently
dragged client window.
> Maintain clients.dragged link and explicit drag state

- doc/herbstluftwm.txt
- src/ewmh.cpp
If a window has multiple window types, then use the first window type
entry. This establishes the behaviour of the 'windowtype' rule condition
from the old herbstluftwm codebase.
This should fix issue #554.
> Use first window type in rules if there are multiple

- ci/build.py
- cmake/debugflags.cmake
These flags are make it impossible to use valgrind or gdb, so those who
need the sanitze flags have to activate them explictly.
This we acitvate them manually in the CI.
> Disable sanitize flags

- NEWS
- src/xmainloop.cpp
If a (unmanaged) dialog has the mouse cursor inside and closes, then an
EnterNotify event is triggered for the next window under the cursor.
With focus_follows_mouse=1 this causes a usually undesired focus change.
> Drop EnterNotify events after unmap

- src/monitor.cpp
- tests/test_stack.py
This avoids that the decoration of a focused window is covered by the
shadow of an unfocused window.
> Always use focus layer in tiling mode

- ci/build.py
- cmake/debugflags.cmake
It makes no sense for a user to build the project with -Werror. Also,
--coverage causes warnings here (even after recompiling in a fresh build
directory). Since both flags are not needed in normal use, the don't
belong to the default configuration, but only to the ci-config (where
it's good to be picky!).
> Move --coverage and -Werror build flags to ci config

- src/monitor.cpp
- src/monitor.h
- src/monitormanager.cpp
- src/monitormanager.h
Move the function that finds a monitor with a given coordinate to the
class MonitorManager. The function is not used at the moment but will be
useful at some point.
> Move monitor_with_cooridnate to MonitorManager

- src/client.cpp
- src/monitormanager.cpp
- src/monitormanager.h
- src/x11-types.cpp
- src/x11-types.h
- tests/conftest.py
- tests/test_monitor.py
When a new client window suggests its window size, it does so by
proposing (x,y)-coordinates relative to (0,0) of the root window. We
now detect within which monitor the new window lies and transform the
coordinates to be relative to that monitor.
If the user puts the clinet window on the monitor within the window's
requested coordinates are, then the client window is precisely at its
requested coordinates. The new test case checks this (both for one and
two monitors).
> Make initial client positions monitor relative

- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/mousemanager.cpp
- src/mousemanager.h
The abstract class MouseDragHandler encapsulates what drag handling
should do: after starting, it is fed with new coordinates whenever the
mouse cursor moves. This is done until mouse dragging stops or until the
dragged resources disappear.
Currently, it's only subclass is MouseDragHandlerFloating that handles
the dragging of clients in floating mode.
The present commit is a step towards mouse resizing in tiling mode
(issue #520).
> Make MouseDragHandler an abstract class

- src/clientmanager.cpp
- src/clientmanager.h
- src/xmainloop.cpp
- tests/conftest.py
- tests/test_rules.py
This adapts the commits 738a0ce and a11e88fc from master to
winterbreeze, and herewith solves #521.
This commit moreover adds a testcase to ensure that the rules are indeed
applied for unmanaged windows ('Override Redirect' in the X11
vocabulary).
> Apply rules to Override Redirect windows as well

- ci/build.py
- src/frametree.cpp
- src/frametree.h
- src/layout.cpp
- src/layout.h
- src/monitormanager.cpp
- src/monitormanager.h
- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/mousemanager.cpp
- src/x11-types.h
In tiling mode, allow the resizing of frames with the mouse. This
loosely is based on ed2cd33 that implements the same functionality in
the old master code base. Still, resizing of empty frames is not yet
possible.
This also disables the 'null-dereference' error check since it
generates false positives for me all the time.
This closes #520.
> Mouse resizing of frames

- NEWS
- src/frametree.cpp
- src/layout.cpp
- src/layout.h
- tests/test_layout.py
When removing a frame, insert the clients of the removed frame in the
target frame at the beginning or the end, depending on how the clients
were aligned visually before the split. Moreover, preserve the client
focus.
In total, the new semantics of the 'remove' command is less 'removing
the frame' but more 'undoing the split'.
> Preserve focus and client order after frame removal

- doc/herbstluftwm.txt
- src/frametree.cpp
- tests/test_layout.py
When removing a frame whose direct sibling is a frame-split itself, then
move the clients of the removed frame to the closest child frame of the
sibling, and not the focused one.
This also adds a test case and consequently solves #593.
> Move clients to closest frame in nested split

- doc/herbstluftwm.txt
- src/settings.cpp
- src/settings.h
This adapts 40e2a2ce85e7 to winterbreeze.
> Make 'verbose' setting modifiable at run-time

- src/layout.cpp
The selection can be at most clients.size() - 1, so enforce it to be at most this bound. Technically, the overflow can not happen, because if the n'th window in a frame with n windows is removed then the line before already decreases 'selection' by 1.
> Fix clamping in HSFrameLeaf::removeClient()

- src/command.cpp
- src/command.h
Move the function declarations of the completion functions from
command.h to command.cpp and make them static. This helps us finding
unused functions in the old completion code.
> Make old completion functions static

- README.asciidoc
Travis image was pointing to the wrong branch and the tutorial URL was
not referenced in correct asciidoc syntax.
> Fix URLs in README.asciidoc

- src/monitormanager.cpp
Do not perform the uniqueness check for a new monitor name if the
monitor name is cleared.
> Clearing a monitor name is always allowed

- cmake/debugflags.cmake
-Wcast-function-type was introduced in gcc8. Make a debug build possible
for older versions by only enabling (in this case disabling...) the
warning only for certain gcc versions.
> Fix Debug build with gcc older than version 8

- NEWS
- src/CMakeLists.txt
- src/monitor.cpp
- src/monitor.h
- src/monitormanager.cpp
- src/monitormanager.h
- src/object.cpp
- src/panelmanager.cpp
- src/panelmanager.h
- src/root.cpp
- src/root.h
- src/xmainloop.cpp
Keep track of running EWMH panels (such as xfce4-panel) and their
position and automatically update the pad-settings for all monitors.
> Detect EWMH panels and update monitor pads

- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/tagmanager.cpp
- tests/test_ewmh.py
Now, Client::setTag() automatically calls ewmh to update
_NET_WM_DESKTOP. Also add testcases for the concrete cases where a
client is moved to a tag via 'load' or 'bring'.
This solves #577.
> Update _NET_WM_DESKTOP in Client::setTag()

- doc/herbstluftwm.txt
- share/autostart
Update default autostart to use boolean values and on the manpage description of `toggle` and `set` (allowed values for boolean settings).
> Update settings types in autostart and manpage

- NEWS
- doc/herbstluftwm.txt
- src/clientmanager.cpp
- src/clientmanager.h
- src/layout.cpp
- src/main.cpp
- src/rulemanager.cpp
- src/rulemanager.h
- src/rules.cpp
- src/rules.h
- src/tag.cpp
- src/tag.h
- src/tagmanager.cpp
- src/tagmanager.h
- tests/test_completion.py
- tests/test_rules.py
The apply_rules command applies all rules to a specified already managed
client. This is useful for experimenting with rules and for the handling
of clients that change their WM_CLASS after the window appears.
> Add apply_rules command

- NEWS
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/clientmanager.h
- src/xmainloop.cpp
- tests/test_rules.py
According to ICCCM, the WM_CLASS has to be set before a client files a
maprequest. Clients (e.g. spotify) that set the WM_CLASS later, lack
the correct WM_CLASS entry when the rules are evaluated. Thus, whenever
the WM_CLASS of an existing client changes, apply the rules again such
that the rules matching against the class name are taking into account.
This solves #643.
> Apply rules on clients whose WM_CLASS changes

- doc/herbstluftwm.txt
- src/clientmanager.cpp
- src/clientmanager.h
- tests/test_rules.py
Add a switch --all to apply_rules that re-applies the rules to all
(managed) clients.
> Allow to re-apply the rules to all clients

- tests/conftest.py
Allow the xlsclients -l to fail if the display has been closed already.
> Allow xlsclients to fail if display is closed

- src/client.cpp
The other event mask may trigger an xlib error if we activate it to
early: herbstluftwm: fatal error: request code=14, error code=9
> Only listen for PropertyChangeMask early

- tests/conftest.py
CI is flaky at the moment, possibly because the xdotool was missing the
sync flag for the relative mouse movement in the 'drag' test.
> Sync relative mouse movements in test fixture

- tox.ini
We introduced a custom pytest marker to exclude some tests from the
coverage report. pytest wants these markers to be registered, so silence
the warning by doing so.
Fixes #656
> Register custom pytest marker

- tests/conftest.py
- tests/test_mousebind.py
- tests/test_x11.py
In the x11.create_client() function, wait for hlwm to empty its X event
queue. By this we are sure that everything related to managing the
client is completed.
Hopefully, this makes the test case test_drag_move more stable. It
definitely fixes a race condition, but I'm unsure whether there is
another one.
Many thanks to @The-Compiler and @blarz who helped a lot with debuging
this unstable test case!
> x11.create_client() wait for hlwm to process

- src/xconnection.cpp
Avoid warnings and unnecessary casts.
> Fixes in XConnection::connect()

- NEWS
- doc/herbstluftwm.txt
- src/main.cpp
- src/root.h
- src/xconnection.cpp
- src/xconnection.h
We can use this in the CI testsuite in the future to avoid even more
errors. Currently, there are some tests that produce xerrors.
> New flag --exit-on-xerror for automated testing

- share/autostart
Not really necessary, but better safe than sorry.
Also makes shellcheck relax.
> autostart: Add some double quotes

- src/clientmanager.cpp
- src/ewmh.cpp
- tests/test_rules.py
Do not crash for the rule tag=sometag when no tag named 'sometag'
exists. We fix this in two places: where the tag name is looked up and
in the EWMH function that updates the EWMH tag property of the window,
just to be sure.
Thanks to @fiete201 for finding and reporting this issue.
> Fix rule consequence for invalid tag names

- doc/herbstclient.txt
- doc/herbstluftwm-tutorial.txt
- doc/herbstluftwm.txt
- share/autostart
There are also some things I wasn't brave enough to edit as I'm not sure about them/didn't know how exactly to do that:
* herbstclient has in its bugs that it waits endlessly, while this is not true now
* also detection via xrandr works (tutorial — pre-last paragraph; main manpage — detect_monitors)
* `complete` — now completion works also with zsh and fish ("because there is already completion for *bash*")
* `keymask` in RULES section deserves a link to its explanation in OBJECTS
> Minor fixes in manpages

- src/frametree.cpp
- tests/test_layout.py
When replacing the root frame, make sure it has no parent.
Otherwise smart_frame_surroundings draws frame surroundings...
Fixes bug #597
> Fix replacing the root frame

- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/mousemanager.cpp
- src/mousemanager.h
- tests/conftest.py
- tests/test_mousebind.py
In the 'drag' command, fail and print an error message if dragging
fails. For mouse events, print the reason for the failure of dragging to
HSDebug().
> Print error messages if dragging fails

- src/client.cpp
Do not call HSFrame::getGloballyFocusedFrame() in the Client class to
get the focused client. Instead use the 'focus' member of the
ClientManager.
> Do not access the focused frame in client.cpp

- src/client.cpp
- src/client.h
- src/ewmh.h
- tests/conftest.py
- tests/test_clients.py
During the refactoring, we somehow lost the attributes 'class' and
'instance' of client objects. This brings them back and adds a test case
for them.
This resolves issue #687.
> Bring client object attributes for WM_CLASS back

- src/plainstack.h
- src/stack.cpp
- src/stack.h
- src/tag.cpp
When changing the floating state of a tag, we add the tiled clients to
the floating layer. We now do this at the bottom, such that they do not
cover the single-floating windows.
> Insert at bottom of stack for global floating

- src/utils.cpp
- src/xmainloop.cpp
- tests/test_rules.py
We apply the rules to all unmanaged windows when they appear (e.g. for
rules) as introduced by 738a0ce5914aee44c9f3d3e559c1c18af6c55c36 and
ported by a2ecbe5da746f56adb7e7f6cda165cc8e7d1c6a7. This makes no sense
for our own frame windows and even is harmful sometimes (see new test
case that failed before this commit), because 'once' rules get
destroyed.
> Do not apply rules to own unmanaged windows

- src/clientmanager.cpp
- src/clientmanager.h
- src/ewmh.cpp
- tests/conftest.py
- tests/test_rules.py
Automatically unmanage desktop and panel windows and float dialog
windows. These rules are hard-wired in client manager, but their results
still can be overwritten by the rules of the user.
> Hard-wire rules for some EWMH window types

- src/client.cpp
This essentially reverts b56e70400f880727f994a86e26aece73cc1004cb that
introduced the cast before multiplication (and not after).
> Fix application aspect ratio size hint

- src/ewmh.cpp
- src/floating.cpp
- src/layout.cpp
- src/layout.h
- src/main.cpp
- src/xmainloop.cpp
- tests/conftest.py
- tests/test_basic_events.py
Especially when focusing a client via a taskbar or 'jumpto', it must be
raised as well. However, if a client is focused only because of a mouse
hover (focus_follows_mouse), then it should not be raised.
Also add tests for raising/focus via mouse clicks and mouse hover.
> Raise client after focus if sensible

- ipc-client/ipc-client.c
- ipc-client/main.c
- tests/test_herbstclient.py
If in the herbstclient main, the HCConnection pointer is null, we do not
free it. This avoids a segfault.
Also add a test case for this.
> herbstclient: do not crash if there is no display

- NEWS
- doc/herbstluftwm.txt
- src/clientmanager.cpp
- src/clientmanager.h
- src/ewmh.cpp
- src/ewmh.h
- src/main.cpp
- src/root.h
- src/tagmanager.cpp
- src/xmainloop.cpp
- src/xmainloop.h
- tests/conftest.py
- tests/test_ewmh.py
- tox.ini
On startup, restore the list of desktops from the EWMH properties on the
root window, and move all clients to the desktop in which they were
before hlwm was started.
Also add test cases for both.
> Move initial clients to their original desktop

- src/xmainloop.cpp
- tests/test_ewmh.py
This fixes a bug that exists since df7d2717, because I didn't understand
the dwm sourcecode back than. On startup, the window manager must also
manage the clients that already exist. Since dwm uses the transient-for
hint to place dialog windows smartly (namely on the same tag as their
master window), dwm first processes the non-transient-for windows and
then the transient-for windows afterwards.
Back then, I only had the second part as a comment and then removed it
in 92c54e1da. Leading to the bug that all transient-for-windows were
ignored on hlwm startup. (For example the 'About' dialog of thunar is a
transient-for-window)
the present commit fixes this bug and adds a test case to avoid this in
the future.
> Do not ignore transient-for-windows on startup

- src/keycombo.cpp
- src/keycombo.h
- src/keymanager.cpp
- src/keymanager.h
- tests/test_keybind.py
When initializing a KeyMask, also set the str member. Also move the
sourcecode regarding matching from KeyCombo to the KeyMask class.
This fixes issue #713.
> Save regex source of keymask, since it's needed

- NEWS
- doc/herbstluftwm.txt
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/keymanager.cpp
- src/keymanager.h
- src/rules.cpp
- src/rules.h
- tests/test_keybind.py
- tests/test_rules.py
The current winterbreeze implementation of keymask was wrong (negated).
Since this is proven to be useful, to block certain keybindings for
concrete clients, we call this feature 'keys_inactive'.
This makes 'keymask' currently an attribute without any effect. The next
step is then to bring back the old behaviour of 'keymask'
See also #713.
> Introduce keys_inactive client attribute

- src/client.cpp
- src/keymanager.cpp
- src/keymanager.h
- tests/test_keybind.py
Implement the keymask attribute (with the meaning as in 0.7.1 and in the
docs). Also add some test cases for it; they are essentially the negated
cases as for keys_inactive.
Also add some more test cases for keys_inactive to ensure that this
commit does not mess up the logic of that.
> Reimplement keymask

- src/monitor.cpp
- tests/test_stack.py
This improves the look and feel of compositor shadows. This
reestablishes the feature of 622cafe534 (#566), but now it does not
interfere with (global) floating mode or the floating layer since we
only raise them within the tiling layer.
> Raise tiled focused clients

- src/client.cpp
- src/layout.cpp
- tests/test_layout.py
Handle smart_window_surroundings entirely in HSFrameLeaf::
computeLayout() and not (as formerly) in Client::resize_tiling(). Here,
we have all the necessary data available to decide whether the
window_gap needs to be applied or not.
Due to the migration, the relevant code in Client has been turned into a
commend, and with the rewrite/cleanup the client has no access to the
frame it lives in.
Also add a test case to check that the new computations are correct.
This solves issue #721. Thanks to @tiosgz for reporting this!
> Fix active smart_window_surroundings

- src/clientmanager.cpp
- src/xconnection.cpp
- src/xconnection.h
- tests/conftest.py
- tests/test_rules.py
Some dialog windows have window type 'normal', but have the
transient-for hint set, which refers to the main application window.
These dialog windows should be floated automatically (unless the user
defined rule say something else).
This closes #723.
> Auto float windows with transient-for hints

- src/ewmh.cpp
- src/ewmh.h
Thanks to XConnection::getWindowPropertyWindow(), this is now a
one-liner in Ewmh::readInitialEwmhState().
> Remove unused Ewmh::readClientList()

- src/frametree.cpp
- src/frametree.h
Adjust FrameTree::cycle_frame() to make it more useful when we cycle
through tiling and floating clients.
> Make interface to cycle_frame more abstract

- src/frametree.cpp
Explicitly cast it instead of the '1ul' suffix. This fixes the
compilation on 32 bit systems.
> Cast 1 to (size_t) before std::max()

- src/tagmanager.cpp
- tests/test_floating.py
Bring back the old behaviour of the 'floating' command that toggled the
state for the current tag if no arguments were passed.
This solves issue #734.
> Let floating accept no arguments

- src/monitordetection.cpp
In xrandr and xinermaa monitor detection, do not proceed if null
pointers are returned. I'm not sure whether this fixes any bug, but it's
better to be on the safe side.
> Check pointers returned by monitor detectors

- src/monitordetection.cpp
Check the existence of the xrandr extension on the display before
calling XRRGetMonitors(). Maybe we even need to check the version.
> Check whether xrandr exists on x server

- src/xconnection.cpp
Only exit if --exit-on-xerrors was specified. Otherwise, print the error
to stderr and keep running
> Do not exit on X errors

- src/monitordetection.cpp
XRRGetMonitors() requires at least version 1.5. Check this, before
calling XRRGetMonitors().
> Check randr version before XRRGetMonitors()

- cmake/debugflags.cmake
- src/ewmh.cpp
Also enable the narrowing warning in debug builds again, now this is
fixed.
> Fix narrowing warning in ewmh.cpp

- src/frametree.cpp
- src/frametree.h
This is another step towards #732. Here, the implementation of the
cycle_all command is separated from the command, and even the wrapping
is now configurable. So now, it's easy to let cycle_all also traverse
the floating windows.
The test cases still fully cover the functionality as it is at the
moment.
> Separate cycle_all implementation from command

- CMakeLists.txt
/usr/share/bash-completion seems more commonly used than the previously
used /etc directory.
Fixes #736
> Install bash completion file to a more common dir

- NEWS
- doc/herbstluftwm.txt
- src/frametree.cpp
- src/frametree.h
- src/x11-types.cpp
- src/x11-types.h
- tests/test_layout.py
A new frame index 'e' specifier that finds an empty frame as close as
possible to the focused frame.
This implements #710.
> Frame index for empty frame

- NEWS
- doc/herbstluftwm.txt
- src/layout.cpp
- src/monitor.cpp
- src/settings.cpp
- src/settings.h
- src/tilingresult.h
This improves the appearance when a compositor is used.
This implements #673.
> Explicitly hide covered windows in max layout

- ci/check-using-std.sh
Assuming that the magic %*/ construct serves no special purpose, using
/../ is more self-explanatory and (as we just learned) less error-prone.
> Simplify reporoot definition in CI script

- src/layout.cpp
- src/tilingresult.cpp
- src/tilingresult.h
The operator[] should not have side-effects (I ran into very unexpected
behaviour when calling 'res[client]' multiple times without know that it
adds element to the vector). For clarity, make it a function named
'add()'.
> Explicitly provide add() function in TilingResult

- src/attribute_.h
Missed the headers in the previous clang-tidy run
> Add another empty() call

- .clang-tidy
These checks used to fail when initially adding clang-tidy to the pipeline.
The underlying issues have probably been fixed in the mean-time.
> Enable some clang-analyzer-unix checks

- src/main.cpp
There is no point in this being static, and it makes pointers to
stack-local variables bleed out of the scope of this function
(clang-tidy complains about this).
> Make long_options for getopt not static

- tests/conftest.py
For some reason in the test suite, the display sometimes closes during
the initialization phase. My only explanation for this is that the
display still exists from a previous test case and that this display is
about to close.
One attempt is to simply retry opening the connection after two seconds.
It will take some time until we'll see whether this works around the
issue.
> Retry if the display closes during X startup

- src/ewmh.cpp
- src/ewmh.h
- src/rules.cpp
- src/xmainloop.cpp
Nearly all these globals are only used in the Ewmh class anyway. And for
the few occasions where it's needed outside of Ewmh, provide a getter
function.
This only moves the variables but does not rename them, which is in the
scope of a separate commit.
> Make globals from ewmh.cpp members of Ewmh

- src/ewmh.h
This is only used in two places, right in that file. It pollutes the
namespace, and triggers a warning for the clang-tidy check
bugprone-macro-parentheses. It is probably not worth it.
> Remove ENUM_WITH_ALIAS macro in ewmh.h

- src/floating.cpp
- src/floating.h
- src/tag.cpp
This makes the resize command also work for clients in floating mode at
resizes the window into the specified direction to the next visible edge
on the screen. If growing is not possible anymore, then the window
shrinks again.
The current implementation does not work entirely for windows with
sizehints, such as terminals: if the resize delta is within the size
granularity, the current algorithm thinks that a resize is not possible
instead of looking for the next edge.
> First draft of keyboard resizing in floating mode

- NEWS
- doc/herbstluftwm.txt
- src/floating.cpp
As a follow up to #790 / b3e6419, make the keyboard resizing of floated
clients also work for floated clients with sizehints. The code is
getting a bit messy, but I leave the clean-up for future PRs.
> Keyboard resizing of sizehints clients

- src/floating.cpp
- src/monitormanager.cpp
- src/monitormanager.h
This replaces the FOR loop macro, by either foreach loops or by explicit
for loops. Sometimes, we need indices in foreach loops, so we need to
explicitly count the index there. (I find this easier to read than an
explicit for-loop with iterators).
> Get rid of FOR macro

- NEWS
- src/command.cpp
- src/command.h
- src/keymanager.cpp
- tests/test_keybind.py
It is a common mistake to forget the 'spawn' in keybinds to commands.
Now, the keybind already fails if the command does not exist. Before,
the keybind succeeded and the command failed silently when the key was
pressed.
> Let keybind check if the command exists

- src/ewmh.cpp
- src/ewmh.h
Make the member variable names fit into the naming scheme of camelCase
with underscore-suffix. The rename was done using qtcreator's
refactoring tool.
Also remove the WM_STATE member variable, because the atom it holds is
already contained in the wmatom_ array.
> Rename Ewmh member variables

- doc/CMakeLists.txt
Since we do not generate the xml ourselves, it does not help us if the
xmllinter finds something to complain about.
This solves #575.
> Disable xmllint in man page generation

- .clang-tidy
- ipc-client/main.c
Found by clang-tidy. Returning in case of argc being 0 should be fine.
Also enable the correspoding clang-tidy check now.
> hc: Fix a potential malloc of zero

- NEWS
- src/tag.cpp
- tests/test_layout.py
There is no need to adjust the description of the cycle_all command in
the man page because it is still/again true that cycle_all traverses all
windows and frames on a tag.
This fixes #732.
> Make cycle_all traverse also floating clients

- cmake/debugflags.cmake
It appears that the underlying issue triggering the warning has been
fixed by now, so this suppression is not necessary anymore.
> Drop -Wno-error=cast-function-type flag

- ci/Dockerfile.ci-eoan
- ci/Dockerfile.ci-trusty
This used to be necessary, but it is not anymore. Leaving it out, should
speed up the build a bit, due to smaller image sizes.
> Remove git from Docker images used for CI builds

- src/layout.cpp
- tests/test_clients.py
- tests/test_floating.py
Basically reverts changes from 41ec3f1d7afcdaabacf6a9e46a8b141a8f9e96c5
but considers floating clients, too. Add some tests, of course.
Fixes #818
> Fix 'bring' if the client is on the same tag

- NEWS
- src/keymanager.cpp
- src/regexstr.cpp
- src/regexstr.h
An empty string is not allowed in the Posix grammar for extended regular
expressions. On openbsd, this led to a run time error on startup
because we initialize the keymask regexes with the empty string.
In the keymask code, we are using the empty string anyway as a special
case for an 'inactive' or 'unset' regular expression, so there is no
need to compile the regex for "".
Thanks to Lucas <lucas@sexy.is> and Florian Viehweger
<openbsd@out-of-creativity.de> for spotting and reporting this issue.
> Never compile a regex for the empty string

- share/herbstclient.fish
Avoid spaces for partial completions. Fixes #797 with a workaround.
Also only complete herbstclient options where appropriate.
I would appreciate any feedback on the changes.
A small present for 0.8 release :smile_cat:
> Update fish completion script

- NEWS
- doc/herbstluftwm.txt
- src/tag.cpp
- tests/test_layout.py
Recently the 'resize' command became also functional in the floating
mode, where the 'FRACTIONDELTA' parameter is not used at all. In the
tiling mode, the parameter is most likely '0.02' for most people. Hence,
it makes sense to make the parameter optional, so one can now run e.g.
herbstclient resize up
to make the focused client (or frame) grow into the upward direction.
> 'resize' command: make delta parameter optional

- src/mousemanager.cpp
If there is no error message, do not print a debug message
> MouseManager: do not print empty debug message

- NEWS
- src/ewmh.cpp
- tests/test_ewmh.py
Make the WM_STATE property of every window have the type WM_STATE, i.e.
apply what is in a5045733. When I originally tried to adapt this commit
to the new codebase I accidentally changed the type back to XA_CARDINAL
(84a6ed87), thus effectively reverting the fix a5045733.
There's also a test case for this now to avoid that this bug is
introduced a third time.
This fixes issue #849.
> ICCCM: Make WM_STATE of type WM_STATE

- src/ewmh.h
- src/hlwmcommon.h
- src/signal.h
- src/stack.cpp
- src/stack.h
Starting with gcc-10, these missing includes are even treated as
errors.
> Add some missing #includes

- doc/herbstluftwm.txt
- src/decoration.cpp
- tests/test_theme.py
The tight_decoration attribute specifies whether the window sizehints
affect the decoration window or only the window content itself. Other
than in the old code base of v0.7.2, we now always center the window if
the size hints change the window size.
This only affects tiled clients with sizehints_tiling enabled. A visual
demonstration of the tight_decoration setting can be found in the
pull-request for this commit:
https://github.com/herbstluftwm/herbstluftwm/pull/858
Effectively, this commit only removes a redundant "if (!false)" and
replaced one "if (false)" by "if (scheme.tight_decoration())". The rest
is documentation and tests.
> Enable theme setting tight_decoration again

- tests/conftest.py
- tests/test_layout.py
I thought I needed the list of frames in another testcase (but
fortunately it turned out that I don't). However, I think it's usefull
to have the get_hlwm_frames() in a separate method for further tests.
> Move frame window collection to x11 fixture

- NEWS
- src/framedecoration.cpp
- src/framedecoration.h
- src/layout.cpp
- src/root.cpp
- src/root.h
- src/tag.cpp
- src/tag.h
- src/xmainloop.cpp
- tests/conftest.py
- tests/test_basic_events.py
This adds basic support for selecting frames with the mouse: either by
click or by mouse hover (if focus_follows_mouse is enabled). This change
only concerns the actual frame. If there is no frame shown (because
always_show_frame=off) or if there is a hole in the frame (because
frame_bg_transparent=on), then we only obtain events for the root window
that are currently ignored. (Interpreting event coordinates on the root
window is in the scope of another change)
On the implementation level, this introduces a static map that
transforms window ids into frame decorations (I think a 'framemanager'
is overkill here). The focusFrame() function is added to the root
window, because it affects the global state of hlwm (and I think
focus_client() should go to Root at some point, too).
This solves …
> Focus frames with the mouse

- src/frametree.cpp
This is probably never an issue, but gcc-10 sees a potential
null-dereference here in case there is no parent.
> Add assertion for parent validity splitCommand()

- doc/herbstluftwm.txt
Use the |-syntax to make it clear that the lines of the description of
tight_decoration belong to the same table cell.
> doc: Fix asciidoc table

- tests/conftest.py
- tests/test_mousebind.py
In the mouse fixture, wait for herbstluftwm to process the ButtonPress
and ButtonRelease events as we were doing it already in the Mouse.click()
method. This should fix the current flakyness of
test_drag_resize_floating_client
> Synchronize mouse press/release with hlwm output

- src/tag.cpp
- tests/test_layout.py
If 'focus' successfully finds another monitor, then it should exit with
returncode 0. Also add a testcase for this.
> Fix exit code of 'focus' command

- tests/conftest.py
- tests/test_mousebind.py
When waiting for hlwm to process the mouse button events, it does not
suffice to wait for the respective 'ButtonPress' or 'ButtonRelease'
debug output on stderr, because this only indicates that hlwm is
starting to process the respective mouse button events. So if we
continue doing something via our own X connection, then the hlwm might
not be finished processing the button event.
Hence, for wait=True, we run the 'true' command because as soon as hlwm
processes some command, we know that the event handling is finished.
We do something similar for mouse move events.
I suppose/hope that this fixes #889.
> Tests: Fix race condition in mouse button fixture

- src/client.cpp
- tests/test_ewmh.py
This fixes issue #586 where a client without wm hints (here, the
chromium window) is equipped with the urgency hint via ewmh, e.g. by:
wmctrl -r Chromium -b add,demands_attention
In such a case, the urgency hint was not updated correctly, and the
tag_flags hook was not fired. This commit fixes both by creating a new
wm hint for clients lacking it instead of doing nothing. Also, a test
for this is added.
> Fix EWMH urgency add for clients without wm hints

- tests/test_herbstclient.py
First read the entire stdout before waiting for herbstclient --idle to
terminate to avoid that writing to stdout blocks for herbstclient.
Maybe this avoids CI failures like this:
https://github.com/herbstluftwm/herbstluftwm/pull/894#issuecomment-623070435
> testing --idle: read stdout before wait()

- tests/conftest.py
In the tests, increase the timeout when waiting for certain lines on
stderr/stdout. A higher timeout should not affect the run time in the
successful case but simply be less picky regarding the scheduling.
> Increase timeout when testing stderr/stdout

- tests/conftest.py
- tests/test_completion.py
This adds a test case that tries to call commands with a junk argument.
Of course this should not affect the coverage, but I hope that with
this, we will find bugs in parser exception handling earlier (such as
pr #590).
> Test feeding junk to commands

- tests/conftest.py
- tests/test_herbstluftwm.py
- tests/test_spawn.py
The issue was that the call() command processed the output of the
herbstluftwm process and so the context manager shutdown code could not
find the strings it was looking for.
There was essentially the same issue in test_spawn that never appeared
in the CI runs (i.e. "in the wild").
The present commit mainly fixes the race condition. While at it, I also
fixed a minor (maybe only theoretic) race condition in
read_and_echo_output() itself, where a line on stdout/stderr was lost if
it is not enclosed by a '\n' byte within the timeout.
This fixes #902.
> Tests: Fix race condition in test_reload

- share/herbstluftwm.desktop
XSession doesn't seem to be a valid type, the spec seems to only mention
Link, Application and Directory. See also
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850690
Also, on my system all other .desktop files in /usr/share/xsessions/
declare themselves to be Type=Application.
> Set .desktop file Type to Application

- src/xmainloop.cpp
DWM ignores these events, too.
> Ignore EnterNotify events by grabs and decoration

- NEWS
- src/monitor.cpp
- src/monitor.h
- src/monitormanager.cpp
- src/monitormanager.h
- src/xmainloop.cpp
- src/xmainloop.h
- tests/test_basic_events.py
This fixes a race condition, reported in #908.
In general, Monitor::applyLayout() possibly drops future EnterNotify
events in the X11 event queue that might have been artifically triggered
because the new tiling on a monitor might have moved a window to the
cursor.
During the handling of an EnterNotify event, no such artificial enter
notify events can be created, because only the focus is changed, so
there is not necessity to drop those. Moreover, on quick mouse
movements, multiple enter notify events can be created if the cursor
traverses over multiple windows. In this case, we must not drop these
later EnterNotify events.
(These events can be triggered while hlwm is already processing the
first EnterNotify event, so it is not enough to skip to the newest
EnterNotify event in the …
> Don't drop later EnterNotify during enternotify()

- src/command.cpp
- src/command.h
They do not seem to be used anymore.
> Remove unused command interface methods

- src/main.cpp
- tests/test_root_commands.py
Also remove one branch that cannot be reached, the argument count is
guaranteed to be larger than 1.
> Add test for invalid jumpto client

- .travis.yml
The flag is deprecated:
DeprecationWarning: The -y flag is no longer supported by Codecov.
codecov.yml must be located underneath the root, dev/, or .github/
directorie
> codecov: Remove -y flag

- tox.ini
pytest-xvfb and PyVirtualDisplay need specific versions to work
together. Also the new flake8 version requires some fixes as it
introduces new warnings (e.g. it warns about f-strings without
parameters).
> tox: Require some fixed package versions for deps

- tests/test_keybind.py
The 'close' command is asynchronous, because it only sends the client a
request to close the window, and it takes some time until the client
reacts. Instead we use the 'add' command which synchronously creates a
new tag.
> Use synchronous commands in keys_inactive tests

- .travis.yml
Overlooked in the last Ubuntu update
> Fix ccache directory names

- tests/conftest.py
With newer versions of PyVirtualDisplay, a display number of :0 can be
valid during tests, too. It does not necessarily mean that Xvfb is not
available.
As suggested by @The-Compiler use the xvfb fixture of pytest-xvfb and
check if it is valid. (You can trigger the assertion by passing
--no-xvfb while running the tests with tox for example).
> tests: Change Xvfb availability check

- tox.ini
PyVirtualDisplay v2.0.0 is out now, which is compatible with the newest PyVirtualDisplay again.
> Unpin pytest-xvfb / PyVirtualDisplay

- HACKING
In order to successfully run the whole suite, you need things like
xdotool and xsetroot.
> Explicitly state addtional pytest runtime deps

- ipc-client/ipc-client.c
- src/xconnection.cpp
The documentation for XGetWindowProperty[1] specifies that if the
format parameter is 32, then the data array must be an array of long.
The present commit fixes this both in the herbstluftwm and in the
herbstclient code.
[1] https://tronche.com/gui/x/xlib/window-information/XGetWindowProperty.html
> X Properties with format 32 are arrays of long

- NEWS
- src/frametree.cpp
- src/monitor.cpp
- src/monitormanager.cpp
- src/utils.cpp
- tests/test_monitor.py
The fear of having an integer overflow caused the modulo implementation to
be wrong for negative numbers in various places of the source code. Of
course, -1 modulo 3 should be 2, and the present commit fixes this
accordingly in the MOD() utility function which is now used everywhere.
> Fix modulo computation for negative numbers

- NEWS
- src/CMakeLists.txt
- src/fixprecdec.cpp
- src/fixprecdec.h
- src/framedata.h
- src/frameparser.cpp
- src/frametree.cpp
- src/frametree.h
- src/globals.h
- src/layout.cpp
- src/layout.h
- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/tag.cpp
- tests/test_layout.py
- tests/test_load.py
We introduce a new class FixPrecDec that encapsulates in- and output of
fixed precision decimal numbers, and we use them for reading and
printing the fractions in the frame layout tree.
This solves #936.
> Use fixed precision decimals for frame fractions

- NEWS
- doc/herbstluftwm.txt
- src/client.cpp
- src/client.h
- src/rules.cpp
- src/rules.h
- src/xconnection.cpp
- src/xconnection.h
- tests/test_rules.py
I use a slightly modified version of `exec_on_tag.sh` to start applications. This works mostly fine with the exception of a starter application forking into the actual application (e.g. eclipse, IntelliJ Idea, Microsoft Teams). For these cases `pgid` is a lot more usefull as it's the same for all applications. With an adjusted timeout and the `once` modifier removed from the rule this leads to the desired behavior of not only having the splash screen but also the actual application spawn on the tag where it was started.
I recon that getting the `pgid` is mostly not trivial but e.g. my small tool [getpgid](https://github.com/wilriker/getpgid) can be used for this purpose.
> Add pgid (process group id) as rule condition

- tests/conftest.py
If we are waiting for the event to be printed by hlwm, there's no need
to pass --sync to xdotool. In some cases 'xdtool mousemove --sync'
hangs, and the present commit tries to work around that issue.
> Do not pass --sync to xdotool mousemove

- tox.ini
Maybe this helps us to find out more about the strange freezes between
test cases (#954).
> Add timeout for each test case

- tests/conftest.py
- tests/test_basic_events.py
- tests/test_mousebind.py
In the setup of the 'mouse' fixture, we reset the cursor to (0, 0). This
now fixes some issues where EnterNotify events were not produced
(because the cursor was already on the window).
In particular, we now support all parameter combinations in the test
case test_focus_client_by_decoration.
> Reset cursor position before every test case

- doc/herbstluftwm.txt
I find a big 'Warning' sign like for 'list_keybindings' too much in the
present case, hence only the inline warning.
> Document that some settings are aliases to theme.

- ci/clang-and-tidy.sh
Gets confused by template methods and reports false positives.
> CI: Disable clang-tidy parameter name check

- .mergify.yml
This uses a new mergify feature where the commit message of a PR is
taking from the opening comment of a PR (which can be edited during the
review of the PR itself). Moreover, this avoids non-sensical comments in
the commit messages like ('Fix typo', 'Fix whitespace', ...).
> mergify: Use pull request title+body as commit msg

- tests/conftest.py
- tests/test_herbstluftwm.py
- tests/test_monitor_detection.py
- tox.ini
This introduces a new fixture 'xvfb' that creates an Xvfb instance
whose scope is only the test case and not the entire test session. The
python code for this has already been written in the MultiscreenDisplay
class.
Having the Xvfb scope only within the testcase gets rid of the necessity
to kill existing/remaining windows at the beginning and the end of the
testcase run.
Moreover, I am passing -noreset to Xvfb, and so the X properties are not
reset when the last client window closes, hence we don't need this
x11_connection fixture hack anymore.
> Create Xvfb manually in the test cases

- NEWS
- src/frametree.cpp
- tests/test_layout.py
If a custom list of layouts is specified for cycle_layout and the
current layout is not part of this list, then cycle_layout has to pick
the first layout in the list according to the docs. The present commit
re-establishes this behaviour and adds test cases for it.
> Fix cycle_layout for omitted layout names

- NEWS
- doc/herbstluftwm.txt
- src/tag.cpp
- src/tag.h
- tests/test_tags.py
This implements feature request #949 in a slightly generalized way.
Though only a boolean was requested, I think having the number of urgent
windows is more future-proof, and one can always transform it into a
'boolean' by running
compare tags.focus.urgent_count gt 0
and checking its exit code.
> New attribute urgent_count for tags

- ipc-client/main.c
- tests/test_herbstclient.py
Some error messages regarding display or herstluftwm availability would still be printed if -q was given.
> herbstclient: Quiet more errors in case of --quiet

- NEWS
- doc/herbstluftwm.txt
- src/rootcommands.cpp
- tests/test_root_commands.py
Equip the new_attr command with an optional argument that initializes
the value of the fresh attribute. While at it, I removed the square
brackets around the type argument, because it looks as if the type
parameter was optional (the type parameter is mandatory). Since it makes
the code easier, I'm also switching to the new ArgParse syntax.
In the man page, I'm not using the term 'initial value', because it is
not the initial value but the second value of the attribute (this can be
relevant in future hlwm versions as soon as it is possible for the user
to hook into the change events of attributes).
> Add initial argument to new_attr command

- src/fixprecdec.cpp
- tests/test_layout.py
An empty decimal would result in a crash
while trying to dereference parts[0] in fixdecprec.cpp.
> Fix crash while parsing empty decimal

- NEWS
- doc/herbstluftwm.txt
- src/frametree.cpp
- tests/test_layout.py
This extends the frame index possibilities by a new character 'p' that
goes back to the parent frame. In order to avoid a mess with 'special
cases' in the frame index section in the man page, I have reorganized it
a bit improving readability.
There is no real way to test frame indices on their own, but I'm using
the 'dump' command which accepts a frame index parameter, in order to
verify that 'dump' prints the correct subtree.
This implements a feature request raised in the discussion of #906 by
elvisjauld.
> Frame index 'p' for accessing parent frame

- src/layout.cpp
- src/layout.h
- tests/test_layout.py
This equips the frame objects with a dynamic attribute 'index'
containing the frame's frame index. Since there is no documentation for
frame objects yet, there is no documentation for the 'index' attribute
here.
This feature has been requested by @bew during the discussion of #906.
> Add 'index' attribute to frame objects

- src/decoration.cpp
- tests/test_rules.py
If multiple floating clients are placed smartly on a tag, then the
'last_scheme' member of Decoration is used to compute the correct
geometry of a client. If this involves clients that have never been
shown, then the 'last_scheme' is not yet initialized.
This commit checks the 'last_scheme' pointer explicitly in
Decoration::inner_to_outer() and adds some test cases which reproduced
the crash earlier. Moreover, I've also added the check in
Decoration::redrawPixmap(), just to be on the safe side.
There is no entry in the NEWS section for this, because this bug was not
present in the last released version.
> Fix crash in smart placement on invisible tags

- src/rules.cpp
- tests/test_rules.py
This adds two test cases for error messages related to the rule
consequence 'maxage'. Moreover, this replaces 'Can not' by 'Cannot' in
the message that needed to be fixed anyway.
> Test messages regarding the 'maxage' rule

- src/argparse.h
- src/main.cpp
- src/mousemanager.cpp
- src/rootcommands.cpp
- src/rules.cpp
- src/tag.cpp
- src/x11-utils.cpp
- tests/conftest.py
- tests/test_mousebind.py
- tests/test_rules.py
There is a subtle difference between the two phrases, and in all
instances in hlwm, 'cannot' is more appropriate.
> Replace 'can not' by 'cannot'

- NEWS
- doc/herbstluftwm.txt
- src/main.cpp
- src/rootcommands.cpp
- src/rootcommands.h
- src/types.cpp
- tests/test_completion.py
- tests/test_root_commands.py
The foreach command iterates over all children of a given object. With
this, it becomes easy to iterate over all clients, tags, monitors. It's
probably only a first version of the 'foreach' because often one needs
to filter the children in a certain way (e.g. 'tags' has more children
than tags because there is something like tags.focus and tags.by-name).
This implements #26.
> Add the 'foreach' command for object iteration

- NEWS
- doc/herbstluftwm.txt
- src/rootcommands.cpp
- tests/test_root_commands.py
This introduces a new format specifier '%c' in the sprintf format
strings. Of course it never makes sense to manually write something like
hc sprintf S '%c.name' 'tags.0'
but it makes sense in combination with the other commands that replace
certain identifiers in commands, especially in combination with the foreach
command.
This change required an update in the completion code for the 'sprintf'
command, and while at it, I fixed a minor bug in the completion. The bug
was that completing the command
hc sprintf S '%s'
erroneously yielded S.
> New constant string format specifier for sprintf

- doc/herbstluftwm.txt
- src/main.cpp
This is long overdue, but herbstluftwm has been lacking the -h and
--help command line flags. On -h and --help, herbstluftwm now prints a
small explanation what it is, prints all command line options and
mentions 'herbstclient' and the man page. I think this is enough for the
time being, because one never interacts manually with the herbstluftwm
binary (only when calling it mistakenly instead of 'herbstclient'
maybe).
> Add -h and --help to herbstluftwm

- .mergify.yml
This makes it easier for me to merge own simple PRs that do not need to
go through a thorough review process.
> Extend .mergify to simplify self-approval of PRs

- src/attribute_.h
- src/indexingobject.h
Using the 'Owner'-aware constructors of DynAttribute_ improve the
readability. The particular constructor removed by this commit was used
in only one place anyway.
This commit does not require new test cases, because there are a couple
of test cases for the attribute 'tags.count'.
> Remove one DynAttribute_ constructor

- tests/test_root_commands.py
This adds a bunch of test cases for the 'compare' command. There are two
deactivated test cases which can be activated as soon as a related (yet
unknown) problem in the Color comparison is fixed.
> Add test cases for compare

- src/rootcommands.cpp
- tests/test_root_commands.py
If compare encounters an attribute of a certain type without an explicit
comparison function, then it should simply use the string
representation for the comparison.
An example is the type of layout algorithms and a test case is added for
that.
> 'compare': fall back to string-based comparison

- scripts/maximize.sh
I often do the following:
1) Call maximize.sh
2) Do some work
3) Later assume this is a "normal" max layout rather than a maximized window, thus press Mod-Space to switch to e.g. grid layout
4) Call maximize.sh again because I want to maximize another window
Instead of a new window being maximized, the layout at step 1) is restored. With this change, if the layout changed in the meantime, it's assumed the user wants to maximize again (just like when there's >1 frame already).
> maximize.sh: Don't restore if layout changed

- scripts/maximize.sh
- Remove 'try' for remove_attr
The underlying issue was fixed, most likely in 5664c64b67f2f44e2e828f6ba231eccab60c5324.
- Make new_attr silent
If we aborted above because the user switched frames/layouts, the my_unmaximized_layout attribute could still exist from the previous run.
> Improve try/silent handling in maximize.sh

- scripts/perclient_kb_layout.sh
Hello and thank you for the HLWM!
What I was missing when switched from Gnome is the feature to keep the keyboard layout bound to windows individually. Thanks to Herbstluftwm flexibility, this can be recovered. I’ve been testing the script for a week or so on a daily basis, works fine, found no problems.
> Add per-client keyboard layout script

- www/compose.py
- www/main.css
This updates the visual layout of the web page in order to make it look
more modern:
- change poisonous colors
- remove the unnecessary frame around the text content such that the
text margin on the left and right more look like the margin around
the text on a piece of paper.
In recent weeks, many spam mails reached the (moderation queue of the)
mailinglist critizing that our web page looks much older and less modern
than those of our competitors; and actually that's true. The present
change tries to fix this.
> www: Abandon frame and poisonous colors

- MIGRATION
- doc/herbstluftwm.txt
- src/tag.cpp
- src/tag.h
- src/tagmanager.cpp
- src/tagmanager.h
- tests/test_tags.py
As stated correctly in #999, this hook would be more useful
if you'd know which tag was renamed.
> Add the old tag name to tag_renamed hook

- src/client.cpp
- src/client.h
- src/layout.cpp
- tests/test_layout.py
As #937 reported, if smart_window_surroundings is enabled, the only
client on a tag correctly uses the minimal theme for surroundings. If
however the client gets an urgency hint, it suddenly uses the normal
theme for displaying the urgent border.
Add a test for this and fix it by caching the most recently used theme
type in order to choose the correct one when drawing the urgent border
(as suggested by Thorsten).
> Fix theme of urgent clients with smart_window

- Makefile
- doc/CMakeLists.txt
- doc/gendoc.py
- tests/test_doc.py
This adds a new script doc/gendoc.py which extracts as much information about
herbstluftwm's object tree as possible. So far, this includes the objects,
their attributes, and possible children. The output format of doc/gendoc.py is
json, so we can pass this information around easily and in fact can verify the
json-formatted documentation by the test suite (more specifically by
tests/test_doc.py).
Motivation
----------
There are three reasons for me starting this:
- Much of the documentation plainly copies information that is already
in the source code
- In the long run, I'd like to have live documentation (something like
a 'help' command as in bash), so in the end the documentation
(including explanations) should be easily accessible for such a
'help' command.
- I'd like to move the …
> Generate json documentation on the object tree

- doc/gendoc.py
- src/child.h
- src/theme.cpp
- src/theme.h
- tests/test_doc.py
This introduces a variation of the Child_<> template called
ChildMember_<> which augments a usual C++ member variable by the
awareness of hlwm's object tree. So e.g. in the DecTriple class, I can
change the types of the members 'normal', 'active', 'urgent' from
DecorationScheme to ChildMember_<DecorationScheme> without changing the
rest of the codebase. This has two advantages:
- It is clear in the class definition, which members are exposed to
the object tree and which are not
- It is easily parsable for doc/gendoc.py, which now fully covers the
theme objects (see the removed exceptions in the test cases)
> Register theme object children via templates

- src/hookmanager.cpp
- src/hookmanager.h
- src/object.cpp
- src/object.h
This removes unused duplicate printing methods that provide a subset of
the features of the `attr` command.
> Remove old debug functions ls() and print()

- .travis.yml
Also switch from curl to wget, which does not print the response body to
stdout on failure. Before, curl printed the error message in html
format, which was piped directly into bash.
> Make codecov interaction optional

- NEWS
- src/client.cpp
- src/clientmanager.cpp
- src/ewmh.cpp
- src/ewmh.h
- tests/test_ewmh.py
A window that is managed but hidden must have WM_STATE=IconicState
whereas hlwm set it to WithdrawnState before. This is described in
ICCCM[1] but also in the implementation note on virtual desktops in
EWMH[2].
Also, when a window is managed but moved to a hidden tag by the rules,
hlwm didn't set WM_STATE at all.
To make it clear to taskbars and pagers that this IconicState does not
mean 'minimized to taskbar', I've added the _NET_WM_STATE_HIDDEN to
_NET_SUPPORTED to make it clear that hlwm would set _NET_WM_STATE_HIDDEN
flag if a window was minimized.
Both these bugs regarding WM_STATE are fixed by the present commit and
checked via test cases.
[1] https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.3.1
[2] https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035376813792
> Fix the value of WM_STATE for hidden windows

- NEWS
- doc/gendoc.py
- src/child.h
- src/object.cpp
- src/object.h
- src/tag.cpp
- src/tag.h
- tests/test_doc.py
- tests/test_tags.py
This allows that a child entry of an object is not an explicit Object*
but a lambda instead that dynamically returns the Object* in this child
entry. This is usefull for entries that are indirectly determined by
other values. For those entries it would be much more coding effort to
keep the links up to date, so instead we just look the information up
when the information is queried, just as in the case of DynAttribute_.
> Add dynamic children DynChild_<> for objects

- ci/diff-json-doc.py
The script `ci/diff-json-doc.py` creates a diff of the output of the
gendoc.py script, and optionally posts this diff as a comment in a PR
discussion. Hence, we directly see how a PR affects the object system.
We should consider adding this to the travis-ci. I found the article
https://damien.pobel.fr/post/github-api-from-travisci/ very helpful
while writing the diff-json-doc.py script.
> Add util to post json-doc diff to github comment

- NEWS
- src/ewmh.cpp
- src/indexingobject.h
- src/tag.cpp
- src/tag.h
- src/tagmanager.cpp
- tests/test_ewmh.py
- tests/test_tags.py
This requires the respective array operations in the IndexingObject and
also it requires that the EWMH properties are updated accordingly.
While writing test cases for that, I noticed that the EWMH properties
are not updated properly when a tag is removed (this changes the index
of the clients on later tags).
The wiring of the signals now solves both issues.
> Make index attribute of tags writable

- NEWS
- src/frametree.cpp
- src/frametree.h
- tests/test_layout.py
This focused_frame child points to the focused frame leave and allows to
inspect the frame that is currently focused, e.g. its layout:
herbstclient attr tags.focus.tiling.focused_frame.algorithm
This prints the layout algorithm used in the currently focused frame,
and thus solves issue #71.
> Add focused_frame child in the tiling object

- doc/gendoc.py
- src/attribute.h
- src/child.h
- src/clientmanager.cpp
- src/entity.h
- src/frametree.cpp
- src/link.h
- src/tag.cpp
This contributes the following:
- A new C++ base class HasDocumentation is added. It has a member
function setDoc() which allows to set user documentation within the
hlwm source code. So far, there is no functionality to pass the doc
string further to the user
- doc/gendoc.py is extended such that it reads these invocation of
setDoc() and puts this documentation text into the hlwm-doc.json
> Parse doc string from sourcecode

- doc/gendoc.py
Sort input file list
so that `hlwm-doc.json` builds in a reproducible way
in spite of indeterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on reproducible builds for openSUSE.
> Sort input file list

- src/client.cpp
- src/client.h
- src/tag.cpp
- src/tag.h
This extends the tag and client objects by a new read-only attribute
'visible'. It indicates whether a tag (resp. client) is shown on the
screen at the moment.
The information is there anyway, and I found it helpful when debugging
the first drafts of the window minimization code.
> Expose visibility information via the object tree

- doc/CMakeLists.txt
Make man page date reproducible
See https://reproducible-builds.org/ for why this is good
CMake already uses `SOURCE_DATE_EPOCH` for `TIMESTAMP`
The SOURCE_DATE_EPOCH variable is documented in
https://reproducible-builds.org/docs/source-date-epoch/
Also use UTC to be independent of timezone.
This is mostly a rebase of #553 that I finally managed to test on 0.9.0 now.
This PR was done while working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
> Make man page date reproducible

- doc/gendoc.py
This sorts all the dicts that are written to hlwm-doc.json. Also we, now
process all the constructor arguments at the very end when all source
files have been read entirely. Before, this had been done after each and
every input file.
> Sort entries in hlwm-doc.json

- NEWS
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/clientmanager.h
- src/floating.cpp
- src/layout.cpp
- src/link.h
- src/root.cpp
- src/tag.cpp
- src/tag.h
- tests/test_clients.py
- tests/test_completion.py
- tests/test_ewmh.py
- tests/test_tags.py
This adds a new attribute 'minimized' that hides a client until it is
unminimized. Only floating clients can be minimized, so we move a tiled
client from the 'tiling' to the 'floating' structures in a tag. Such a
client still has 'floating' set to false and will be moved back to the
tiling layer if it gets un-minimized.
It is important that hlwm ensures that minimized clients can not be
focused. If a minimized client shall be focused, it has to be
unminimized first. This is not yet respected by the present PR in the
cycle_all command but must be implemented next.
There is no way to manipulate the minimization state through
EWMH-Requests, but I found the following keybinding helpful for testing.
herbstclient keybind Alt-m attr clients.focus.minimized toggle
> Implement client minimization

- src/tag.cpp
- src/tagmanager.cpp
- tests/test_tags.py
This sets the visibility of minimized clients correctly when they are
moved between tags. The test cases for it use the 'apply_rules' command
to move a client between tags since there is no direct way to do so via
the object system but it is possible via EWMH (see the test case
test_ewmh_move_client_to_tag), but I wanted the test cases in the
present change to be independent of X11.
> Fix moving a minimized client between tags

- src/frametree.cpp
- tests/test_load.py
This makes the 'load' command handle minimized clients correctly and
adds test cases for it. I'm also setting 'floating' to 'false', since
the client is sucked into the frame tree by the 'load' command and thus
definitely not in the floating state anymore.
> Correctly 'load' minimized clients to a frame tree

- doc/herbstluftwm.txt
- src/tag.cpp
- tests/test_layout.py
Following the principle of #1032 that minimized clients shall never be
focused or visible, the cycle_all command must skip minimized clients.
This implements the skipping of minimized clients and adds a number of
test cases for it.
While at it, I've removed a unnecessary call to the raise() function of
the newly focused client. It was unnecessary because the raise()
function is called anyway at the end of cycleAllCommand() for floating
clients.
> Let cycle_all skip minimized clients

- src/mousemanager.cpp
- tests/test_mousebind.py
It makes no sense to drag a minimized client, so lets be safe and forbid
it.
> Disallow 'drag' for minimized clients

- src/layout.cpp
- tests/test_floating.py
If a minimized tiling client is passed to 'bring' hlwm crashed because
is_client_floated() returned false but the client was also not
contained in the frame tree. To fix this, we do the following:
- Un-minimize the client first such that a minimized and tiled client
already is in the frame tree when looking for the client in the
frame tree.
- Explicitly check whether the client is in the frame tree instead of
indirectly relying on is_client_floated().
Hopefully, this fixes #1037.
> Fix 'bring' for minimized clients

- src/rulemanager.cpp
- src/rules.cpp
- src/rules.h
This moves the rule evaluation code into the class Rule. This has the
advantage that (a) the RuleManager does less member access to members of
the Rule class and (b) we can implement a command for applying a
standalone rule to a given window without adding the rule to the full
rule list.
> Make rule evaluation a member function of Rule

- src/rulemanager.cpp
- src/rulemanager.h
This is another step towards a command that applies a single temporary
rule. Since this does not change hlwm's behaviour, the existing set of
tests in test_rules.py should be sufficient.
> Make rule parsing a static member of RuleManager

- src/argparse.cpp
- src/argparse.h
- src/tag.cpp
- tests/test_layout.py
This adds support for command line flags to the ArgParse class. A flag
can appear at any position in the command line arguments between the
(mandatory or optional) positional arguments. A flag is usually prefixed
with one or two dashes, but there is no formal requirement for this in
the ArgParse implementation.
A unknown flag will simply be ignored and parsed as a positional
argument instead. This is because I don't want negative numbers on the
command line to be misinterpreted as unknown command line flags.
For illustration and testing, this migrates the focus command to ArgParse with
flags.
> Extend ArgParse with boolean command line flags

- NEWS
- doc/herbstluftwm.txt
- src/finite.h
- src/frametree.cpp
- src/frametree.h
- src/main.cpp
- src/types.h
- tests/test_layout.py
This adapts the 'mirror' implementation from the PR #93 to the new
codebase. Additionally, it accepts a positional argument along which
axis the layout is to be mirrored.
On the implementation side, it uses type_traits and a new 'is_finite'
predicate to avoid boilerplate code when instantiating the Converter
class to the enum class type Horizontal/Vertical/Both. There is still a
bit to write, but much less compared to the Converter-implementation for
the ClientPlacement class.
In order to make Converter applicable to type traits, a new template
parameter to Converter "typename = void" was necessary.
> New command 'mirror' for mirroring the frame tree

- src/framedata.cpp
- src/framedata.h
- src/rootcommands.cpp
- src/rules.cpp
- src/rules.h
- tests/test_layout.py
- tests/test_root_commands.py
This simplifies the Converter implementations of the types SplitAlign,
LayoutAlgorithm, ClientPlacement, and also of a new type CompareOperator
that is now used in the input processing of the 'compare' command.
> Use Converter for Finite class where possible

- src/tag.cpp
- tests/test_layout.py
Migrate cycle_all to the new ArgParse and add tests for the standard
error messages. There are already tests for cycle_all, so this also
covers the successful parsing of the flag and the positional argument.
> Use ArgParse in cycle_all

- NEWS
- doc/herbstluftwm.txt
- src/clientmanager.cpp
- src/clientmanager.h
- src/main.cpp
- src/rulemanager.cpp
- src/types.h
- tests/test_rules.py
It applies a temporary rule to one particular or all clients without
modifying or evaluating the existing rule set. I made the
error messages of the rule parser generic in the command name where
possible. There are still hard-coded 'rule:'-prefixes in error messages
in setLabel(), addCondition(), and addConsequence() in the Rule class,
but I didn't want to blow up neither the argument list nor this PR.
> Add the 'apply_tmp_rule' command

- tests/test_ewmh.py
This fixes a race condition in a test case using wmexec. The race
condition occurred in the debian build log
https://buildd.debian.org/status/fetch.php?pkg=herbstluftwm&arch=ppc64el&ver=0.9.0-1~bpo10%2B1&stamp=1607007505&raw=0
and consists of the magic string "hlwm started" showing up to early such
that the read_and_echo_output() within hlwm.call() consumed it
and not the read_hlwm_output() in the test case.
As a fix, we use the unchecked_call() for which we can deactivate the
consumption of hlwm output.
I've successfully reproduced the race condition by updating the test
case to:
@pytest.mark.parametrize('n', range(0, 200))
def test_tags_restored_after_wmexec(hlwm, hlwm_process, n):
and passing read_hlwm_output=False fixes it.
> Fix race condition in test_tags_restored_after_wmexec

- INSTALL
Maybe clears up some confusion that was mentioned in #1053
> Fix INSTALL formatting, add out-of-tree build dir

- INSTALL
Render lists correctly by adding blank lines around them and
render the Mac OSX Xmodmap section as code.
> INSTALL: More asciidoc fixes

- ci/build.py
- python/README.md
- python/herbstluftwm/__init__.py
- python/setup.py
- tests/conftest.py
- tox.ini
This initiates python bindings to herbstluftwm. The purpose of this is
to make it easier to write python scripts for hlwm. Moreover, as soon as
there are more useful functions in the bindings, we can also make use of
them in the test suite. Thus, we don't need a dedicated testsuite for
the bindings.
So far, the only functionality is call(), unchecked_call(), and
argument parsing.
> Add basic python bindings

- src/frametree.cpp
- src/layout.cpp
- tests/test_layout.py
In FrameLeaf::split(), the function FrameLeaf::setSelection() was called before
`selection` was (and could be) set correctly. Since setSelection() called
Monitor::applyLayout(), this led to a crash because the `selection` was out of
bounds.
The present change removes all invokations of Monitor::applyLayout() from
setSelection() (the only leftover use of applyLayout() in FrameLeaf/FrameSplit).
To ensure that the actual window geometries update correctly, I went
through all invocations of setSelection and added the applyLayout() where it
wasn't called before (namely, the commands focus_nth and cycle). The other
commands (cycle_all, remove, focus) called applyLayout() already.
Also, I removed the call `clients[selection]->window_focus()` because it is
simply wrong if the FrameLeaf is not …
> Do not call applyLayout() from FrameLeaf

- python/herbstluftwm/__init__.py
- python/herbstluftwm/example.py
- tests/test_python_binds.py
This simplifies the reading and writing of attributes via the python
bindings. Also, this adds:
- Test cases for thew new AttributeProxy functionality
- example.py showing the example usage (and we call it from the test
suite to ensure that the examples indeed work)
- an utility function for combining commands via chain/and/or
> Add AttributeProxy object for python bindings

- .github/workflows/hlwm.yml
- .mergify.yml
- ci/build.py
This converts the travis ci configuration to github actions. Again we
have three jobs: one with gcc, one with clang, both on a current 64 bit
system, and one on an old 32 bit system.
All three jobs run in docker containers that are pulled from dockerhub.
In the old travis setup, if the docker file changed, then the newer
docker file was used directly. This is not yet reflected in the github
actions, so we can't use pull requests to test changes in the docker
files, yet.
Moreover, the ci/build.py is really optimized towards being invoked only
once, as it was the case for the travis ci. With github actions, we will
need to invoke it multiple times per job (namely step by step), so
ci/build.py will need to change further in the future. I tried to be as
little invasive here as possible to …
> Migrate CI to github actions

- tests/test_root_commands.py
This tests some error messages in attribute_.h that were non-covered
before according to codecov.
> Test exceptions in attribute_.h

- cmake/debugflags.cmake
In the debug build, activate range checks for C++ datatypes. This flag
would have been prevented crash #1056 on fedora, that has these flags
per default. While at it, I've also added further stack protection flags
in the hope that this helps us to detect bugs earlier.
> Use -D_GLIBCXX_ASSERTIONS and other security flags

- NEWS
- doc/herbstluftwm.txt
- src/frametree.cpp
- src/layout.cpp
- tests/test_layout.py
This restores the (desirable) behaviour of 'split explode' from v0.7.2
where splitting preserved which client is focused.
> Make 'split explode' preserve the client focus

- .github/workflows/hlwm.yml
It seems that in #1068 the github actions are run on the fork a pull
reqests contributor, and this does not activate the required status
checks for mergify. Let us try to add 'run on pull request' to solve
this.
> Also run github actions on pull_requests

- doc/herbstluftwm.txt
> Rephrase docs for default 'split explode' FRACTION

- .github/workflows/hlwm.yml
- ci/Dockerfile.ci-focal
- ci/build.py
To avoid cpu and user time, I'm combining multiple smaller changes:
- The build directory is now passed via environment variables
and thus does not need to be specificed in every step
- Only pushing to 'master' triggers the workflow, because otherwise,
every pull request triggers the workflow twice: as a pull request
and for the branch (the latter is run on the repository containing
the branch, not necessarily herbstluftwm/herbstluftwm)
- The 'current ubuntu' dockerfiles now includes git, curl, and wget.
> Minor improvements in CI

- .github/workflows/hlwm.yml
- ci/build.py
According to the GHA docs[1] the cache lookup "first searches for cache
hits for key and restore-keys in the branch containing the workflow
run."
However, it seems that in #1072, it always picks the cache from the
master branch. Hence, in this PR, I'm trying to adjust the ccache
parameters accordingly to make the cache in the 'master' branch as good
as possible.
[1] https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
> Laxer ccache parameters

- .github/workflows/hlwm.yml
Cache entries are never updated, so we need to change the cache keys
every time in order to update the entries.
> Make cache names unique

- NEWS
- src/clientmanager.cpp
- src/rulemanager.cpp
- src/rulemanager.h
- src/rules.cpp
- src/rules.h
- tests/test_rules.py
The commands apply_tmp_rule and apply_rules now print parser error
messages to their output which is forwarded to the invoking
herbstclient. This makes debugging rules easier.
However, on new clients, the error message is still printed to
herbstluftwm's stderr.
> Print parse errors for apply rule commands

- src/layout.cpp
- tests/test_layout.py
This adds tests for the functionality of the 'shift' command and also
clarifies the error message if no client is focused (the message was "No
neighbour found" before).
> Add test cases for the 'shift' command

- ci/diff-json-doc.py
This puts the json diff in the PR comments into a collapsible block. The
diff is shown per default for diffs shorter than 100 lines and is
collapsed per default otherwise.
> diff-json-doc: Collapse longer diffs

- ci/diff-json-doc.py
Add trailing commas after fields, and not only between fields. This reduces the
diff size whenever a new field is added at the end of an object.
> diff-json-doc: Normalize trailing commas

- .github/workflows/hlwm.yml
- INSTALL
- NEWS
- ci/build.py
- doc/CMakeLists.txt
Since tarballs contain the json doc anyway treat the json doc as the
other man pages and only build them if WITH_DOCUMENTATION is activated.
This avoids python as a build dependency for the tarballs.
If WITH_DOCUMENTATION is not set, then we still create an optional make
target which is called in the CI.
Also this marks the installation of the json doc optional, meaning that
it is installed if it has been generated.
> Only build json doc on WITH_DOCUMENTATION

- src/floating.cpp
- src/floating.h
- src/monitor.cpp
- src/monitormanager.cpp
- src/tag.cpp
This moves all floating functions into a common namespace called
Floating. If the function had a prefix floating_ then I already
converted the name to camelCase, otherwise I left the name as it was.
The namespace Floating is implemented as a class with static functions
because in the future, these may become non-static by using member
variables of the Floating class instead of the global hlwm state (as it
is now when calling get_current_monitor() or focus_client()).
This also removes the orphaned declaration char_to_direction().
> Create new Floating namespace in floating.h

- doc/gendoc.py
The class inheritance is relevant for the json doc, because the
FrameTree has children of type `Frame`, and a `Frame` can be a
`FrameSplit` or a `FrameLeaf`.
I have no explicit test for this, but of course the test suite already
tests for the existence of the inherited attributes.
> Document inheritance in json doc

- src/frametree.cpp
- src/frametree.h
The focused frame is always a frame leaf, so the DynChild_ should also
have this type. This just improves the type-safety and hlwm-doc.json.
> Make tag.*.tiling.focused_frame a FrameLeaf

- NEWS
- src/panelmanager.cpp
- src/panelmanager.h
- src/x11-types.h
- src/xmainloop.cpp
- tests/conftest.py
- tests/test_panels.py
If a panel window has the type _NET_WM_WINDOW_TYPE_DOCK but does not
define in _NET_WM_STRUT from which borders of the screen it takes space,
then automatically detect it based on the window's geometry.
This also adds tests for the new functionality and also for the old
panel detection based on _NET_WM_STRUT
> Reserve space for panels without _NET_WM_STRUT

- NEWS
- src/client.cpp
- src/client.h
- tests/test_clients.py
The 'parent_frame' child of a client provides the frame object that
holds the client.
This fixes #6.
> Add 'parent_frame' entry for each client

- CMakeLists.txt
- INSTALL
- doc/herbstclient.txt
- doc/herbstluftwm.txt
- src/client.cpp
Unbreaks install and removes all other references as reported in #1093.
Rather reference the Github issues page everywhere.
> Fix references to removed BUGS file

- share/autostart
- src/decoration.cpp
- src/fontdata.cpp
- src/fontdata.h
- src/main.cpp
- tests/test_theme.py
This uses the XFontSet structure and XmbDrawString routines that are
capable of utf8 encoded strings. The setlocale() in the main is of great
importance, because otherwise, text drawing stops on the first non-ascii
character.
Unfortunately, XCreateFontSet() or XmbDrawString() seem to be
incompatible with the terminus font on my installation.
If the XCreateFontSet fails, then we fall back to plain XFontStruct and
XDrawString.
> Support proper utf8 strings in window titles

- .github/workflows/hlwm.yml
- ci/build.py
This splits the build step in the github action workflow into smaller
steps of cmake, compilation, and installation. Since we now understand
how the cache in github actions work (cf #1075), I've removed the
printf-debug steps.
The --cxx etc flags define environment variables, and they should only
be used during cmake, but not during the ninja compilation. Hence, it
should be sufficient to pass build_env to cmake. The only environment
variable relevant during the build process is CLANG_TIDY_BUILD_DIR which
is now only set in the `build.py --compile` step.
> Make CI steps more fine-grained

- src/byname.cpp
- src/object.cpp
- src/object.h
It is only used by the ByName object and the implementation of
addStaticChild() was identical to addChild(). So, let us remove this
duplicate.
> Remove nearly unused Object::addStaticChild()

- NEWS
- src/monitor.cpp
- tests/test_monitor.py
For some reason, the lock_tag attribute was not writable (even in the
old source code at tag v0.7.2). In fact, the lock_tag and unlock_tag
commands do nothing except setting the attribute.
While at it, I've added a bunch of test cases for the lock_tag attribute
and the respective commands.
> Make the lock_tag attribute writable

- src/child.h
- src/link.h
- src/object.h
The ChildEntry class combines what Child_, ChildMember_, DynChild_, and
Link_ have in common: a owner, an entry name, and documentation.
This ChildEntry can then be used to have a uniform interface for adding
and removing child entries from an object.
While at it, I also make the member variable names have a `_` suffix
and the function parameters have no suffix.
> Avoid redundancy by introducing a ChildEntry class

- ci/Dockerfile.ci-trusty
Hopefully fixes problems with CMake/pkg-config not finding some libs.
> CI: Use i386 pkg-config on trusty

- cmake/dependencies.cmake
- ipc-client/CMakeLists.txt
- src/CMakeLists.txt
Instead of using the FindX11.cmake module that comes with cmake, we now
use pkg-config for the compiler and linker flags. This allows us to
explicitly state which libraries we use. For FindX11.cmake it just
tried to detect what's there, with little output. for pkg-config, cmake
now clearly prints which libraries are found, and which are missing.
This also adds the libraries freetype and xft that will be necessary
for xft font rendering.
> Use pkg-config for library detection

- share/autostart
#1032 added this feature and had that nice keybind command in the commit message.
It fits perfectly into the default autostart.
> Add minimization keybinding to default autostart

- NEWS
- doc/herbstluftwm.txt
- src/entity.h
- src/main.cpp
- src/metacommands.cpp
- src/metacommands.h
- src/object.cpp
- src/object.h
- tests/test_doc.py
- tests/test_meta_commands.py
The 'help' command prints information on a given attribute or object.
The tests so far check that it prints something useful and matches it
against the 'doc' field in the json documentation.
> Add 'help' command

- doc/gendoc.py
- src/client.cpp
- src/clientmanager.cpp
- src/entity.h
- src/object.cpp
- src/object.h
- src/settings.cpp
- src/theme.cpp
- tests/conftest.py
- tests/test_doc.py
This makes Object inherit from HasDocumentation and parses the
respective calls to setDoc() into the json document. The attr command
now prints this object documentation, and this allows us to add test
cases that it matches the doc in the json file.
Note that the object documentation is something different than the
documentation on these "child entries" because e.g. the documentation on
clients.focus is "the focused client" whereas the documentation on
Client is that it represents "a managed window".
> Let objects have documentation

- NEWS
- doc/herbstluftwm.txt
- src/CMakeLists.txt
- src/main.cpp
- src/metacommands.cpp
- src/metacommands.h
- src/root.cpp
- src/root.h
- src/watchers.cpp
- src/watchers.h
- src/xmainloop.cpp
- tests/test_watchers.py
This implements a commonly requested feature allowing to be notified
when an attribute changes. The implementation just saves the value of
the watched attributes and periodically checks if the value has been
changed.
There is still room for optimization: One optimization is to replace the
plain map from string to string to a more advanced structure that speeds
up scanForChanges(); another is to use the signals where possible.
This fixes #1098. Also, this implements the missing piece of #71.
> Add attribute watchers

- NEWS
- src/panelmanager.cpp
- tests/conftest.py
- tests/test_panels.py
The entries of WM_STRUT need to be interpreted with respect to the
borders of the root window (not of the monitor). The present change now
translates WM_STRUT into a rectangle which is then used to allocate
space at the monitor edge.
Only if WM_STRUT is empty, the geometry of the panel window is used as
the rectangle.
Formerly, we ignored WM_STRUT and always used the panel window, which
broke the support for panels that deliberately leave some space around
the panel. I originally took the window geometry, because 1. it was
easier (but as it turned out wronger) than computing the rectangle from
WM_STRUT and 2. this check for the case where the panel geometry and the
WM_STRUT were contradictory, as in #815.
This fixes #1110.
> Correctly interpret a panel's WM_STRUT

- src/panelmanager.cpp
- tests/test_panels.py
Automatically update the padding attributes of every monitor if the
setting auto_detect_panels is changed.
> Update monitor paddings if auto_detect_panels changes

- share/panel.sh
Insert the correct name of the xftwidth textwidth replacement. Now the
content of $textwidth matches the argument to `which`.
Thanks to Bohdan Potměkleč (tiosgz) for reporting. This fixes #1117.
> Fix typo in xftwidth

- doc/herbstluftwm.txt
The object tree is stable and will not change, so we really do not need
this warning anymore; it has been stable already for a very long time.
> Remove the warning from object doc

- src/main.cpp
- src/stack.cpp
- tests/test_stack.py
When raising a slice in a stack, one should not directly forward the
changes to the X-Server, because often raiseSlice() is called multiple
times in a row.
After removing restack() from Stack::raiseSlice(), I've ensured that the
X window order is updated in the end anyway by searching for its
invokations. The raiseSlice() function itself is only called by
Client::raise(), which is called by the following functions:
- In focus_client(), applyLayout() is called immediately after
raise().
- In Monitor::applyLayout(), restack() is called after raise()
- In HSTag::cycleAllCommand(), the signal needsRelayout is emitted
after raise() is called.
- In raise_command(), I'm emitting the signal needsRelayout to ensure
that the restacking takes place. In tiling mode however, the then
called …
> Do not call restack() on raiseSlice()

- doc/CMakeLists.txt
In the current build system, herbstluftwm.html and herbstluftwm.1 were
not rebuilt after hlwm-objects-gen.txt had been changed. The issue is
that this file was only a dependency of the target but not of the
command. The present change makes it a dependency of the command by
passing it as an optional argument to gen_manpage and gen_html
(add_dependencies does not work for extending add_custom_commands, only
for add_custom_target).
> cmake: Fix dependencies between asciidoc files

- doc/format-doc.py
- www/main.css
This adds colors to the attribute names and types and child names in the
object doc. Also, this inserts a colon between the attribute
specification and the doc string.
Moreover, 'code' is an html tag not a class, so main.css had to be
adjusted.
> Add colors to the object doc

- NEWS
- src/frametree.cpp
- tests/test_layout.py
The commands 'mirror' and 'rotate' updated the child frame pointers
explicitly without updating the pointers for the frame objects. Which
caused the frame object tree to be wrong.
The present change fixes this and adds a test for it.
Thanks to @astier for an excellent bug report on this!
Fixes #1151.
> Fix frame objects in 'mirror' and 'rotate'

- tests/conftest.py
- tests/test_decorations.py
This adds a screenshot-based test suite for the drawing of decorations.
The idea is that after changing the theme or other parameters of the
window decorations, we take a screenshot and tell from the pixels
whether everything is drawn correctly.
So far, this contains tests for the main, inner, and outer border color
and tests for the font-rendering.
Also this adds another x11-sync to x11's sync_with_hlwm(), because
syncing with hlwm itself only makes sense if all the client information
is already present at the xserver.
> Add test cases for decorations and fonts

- src/stack.cpp
- src/stack.h
Coverage and grep indicate that those methods are not used anymore.
> stack: Remove unused methods

- tests/test_python_binds.py
Instead of importing it, just invoke example.py as one would from the
command line. Also this will make it easier to adjust the path (#1136).
> Explicitly invoke example.py from bindings

- doc/CMakeLists.txt
The intermediate generated files hlwm-doc.json and hlwm-object-doc.txt
were built multiple times when running 'make -j8' which regularly led to
build failures (run 'touch ../../src/clientmanager.cpp && make -j8' from
build/doc multiple times to reproduce, also note that the two mentioned
files are generated twice).
I first thought that the race condition leading to build failures was
fixed in de44c9ab19b5 (#1155), but the issue still existed.
I don't know whether this is by design of cmake or a bug in cmake.
Nevertheless, the present change works around this issue by creating
named targets for the files hlwm-doc.json and hlwm-object-doc.txt
because now, cmake recognizes the shared dependencies and only builds
them once (even with make -j8).
While at it, I've avoided that the asciidoc …
> Fix parallelism in cmake file for doc

- src/client.cpp
- src/client.h
Coverage and git grep show it's never used.
> client: Remove unused applysizehints_xy

- .github/workflows/hlwm.yml
- Makefile
- ci/mktar.sh
- doc/CMakeLists.txt
In source tarballs, the built documentation is already shipped along
with the tarball. The CMakeLists of doc now detects a prebuilt
documentation, and in this case simply copies the documentation to the
build directory (without requiring asciidoc to be installed).
This implies that one does not need to (and in fact should not) disable
`WITH_DOCUMENTATION` when building a tarball without having asciidoc
installed.
In the CI job for the docs, the tarball is now built and tested. In the
ancient ubuntu build, this tarball is used instead of the source from
the git repo. To be sure that everything worked, the job verifies that
the man page has been installed to the DESTDIR.
> Re-use pre-built doc in tarball builds

- src/decoration.cpp
- src/decoration.h
When using a compositor (e.g. compton or picom), the border of some
windows is sometimes (undesirably) semitransparent for applications with
alpha settings (e.g. sakura or katarakt). This only happens for certain
graphics, I can reproduce it on intel graphics but not on nvidia
chipsets. The issue is probably that the highest significant byte of the
color is not initialized.
In the present patch, this byte is set to 0xff, thus fixing the
byte controling alpha-value to 'fully opaque'. This also used by dwm[1]
and wmutils[2] to fix this issue.
While at it, the return type of get_client_color() is turned into
'unsigned long' because this is the type of xcol.pixel.
This fixes #1173 / #992 
[1] https://dwm.suckless.org/patches/alpha/dwm-fixborders-6.2.diff
[2] …
> Fix transparency of 32 bit client's border

- .github/workflows/hlwm.yml
In the minimalist CMakeLists for the ci build of the docs, the VERSION
file was not yet considered. However, it is needed for the footnote at
the end of the man pages.
> Respect VERSION in CI build of docs

- src/frametree.cpp
- src/frametree.h
- src/tag.cpp
In order to pave the way for #1066, move all the frame-specific code of
the `shift` command to the FrameTree class (where it actually belongs).
No tests are needed because test_layout.py has already enough tests for
the `shift` command.
> Move the tiling part of 'shift' to FrameTree

- src/decoration.h
- src/x11-types.cpp
- src/x11-types.h
- tests/test_types.py
Extend Color by a alpha value and extend the parser and printer to print
colors in the #rrggbbaa format. The alpha value is not used anywhere at
the moment, but it will come in handy for decoration drawing.
Also, this adds a new test suite file dedicated to all the type parsers
and printers.
> Prepare Colors for alpha values

- src/decoration.cpp
- src/decoration.h
- src/main.cpp
- src/root.cpp
- src/root.h
- src/xconnection.h
Instead of using the globals g_display etc, the Decoration class now
only takes the display pointer from the XConnection class.
Also, instead of the 'default screen', the screen number is taken from
the XConnection class.
Since this XConnection is also used in the destructor of decoration, we
should wait with resetting the global Root* variable and first shut all
submodules down.
> Use XConnection in Decoration

- src/xconnection.cpp
If a window disappears right before XGetGeometry() is called, then the
rectangle is not initialized. Hence, just initialize everything before
to be on the save side.
This was detected by address sanitization, reporting that jumps depended
on uninitialized memory, and it was triggered by the qt application
katarakt that creates two windows and hides them instantly again.
> Initialize rectangle before XGetGeometry()

- share/autostart
Stop using the #9fbc00 color as the default border color, since it is a
quite aggressive color. I loved this color, when it was introduced by
pwmt.org applications, but I've stopped using it in my own settings some
years ago and I have the impression that many people don't like it when
starting with hlwm (and the default hlwm config).
Instead, the border color now is the same (dark) green tone as in the
frame border, and is optimized such that it also looks nice with or
without transparency.
> Make default colors more transparent and quiet

- src/CMakeLists.txt
- src/command.cpp
- src/globalcommands.cpp
- src/globalcommands.h
- src/main.cpp
- src/root.cpp
- src/root.h
- tests/test_global_commands.py
- tests/test_meta_commands.py
The GlobalCommands module collects commands that modify the global state
of hlwm and need multiple subsystems (e.g. monitors and tags).
As an example, the tag_status command is migrated, and it's test suite
is moved to the new test_global_commands.py and slightly extended.
> Migrate tag_status to new GlobalCommands module

- NEWS
- cmake/dependencies.cmake
- doc/herbstluftwm.txt
- src/CMakeLists.txt
- src/decoration.cpp
- src/framedecoration.cpp
- src/main.cpp
- src/root.h
- src/x11-types.cpp
- src/x11-types.h
- src/xconnection.cpp
- src/xconnection.h
- tests/conftest.py
- tests/test_decorations.py
- tests/test_panels.py
This adds true transparency support in all frame and client decorations
(using the xrender X11 extension), where the level of transparency is
controlled by the alpha value of the colors. The only instance where the
alpha value does not work yet is at Xft fonts.
Per default, hlwm tries to initialize true transparency on startup (this
can be prevented with --no-transparency).
The test cases for the decoration colors now run in all combinations of
xrender being available at the server and hlwm trying to use it.
For xrender to work, we need to start xvfb with color depth 24 (rather
than 8), and this also results in the screenshots being in a slightly
different format.
On the technical side, the XConnection class now provides a singleton
object getter, which can be used to obtain the pointers …
> Support true transparency in all decorations

- NEWS
- src/framedecoration.cpp
- src/layout.h
- src/x11-utils.cpp
- src/x11-utils.h
For semi-transparent clients, it is unpleasant to see the frame
decoration shining through. Hence, we now cut holes into the frame's
decoration at the area where clients are. If no true transparency is
activated, no difference should be noticeable, and for true transparency,
one sees the wallpaper or desktop window shining through.
Internally, the last 'outer' geometry of every client is used, and so
this also interacts nicely with pseudotiled windows and the grid layout.
This should improve the cosmetics and implicitly also solve #1183.
> Cut holes into frames behind tiled clients

- tests/conftest.py
- tests/test_decorations.py
This adds tests for the XShape functionality in the frame decorations.
This covers both the setting frame_bg_transparent /
frame_transparent_width and the new functionality of hiding the frame
content behind clients (PR #1187 / f7ba8f9940).
> Add screenshot-based tests for frame decoration

- scripts/unminimize.sh
This script offers un-minimization as stated below:
> In my opinion, the best solution would be the unminimization of one window (e.g. the last minimized or the longest minimized window)
see: https://github.com/herbstluftwm/herbstluftwm/issues/1133#issuecomment-760193386
As it is non-trivial, I thought that adding this feature as a script was the best option, but feel free to close this PR if it seems irrelevant.
> Add script to un-minimize clients in a LIFO-way

- doc/gendoc.py
- src/CMakeLists.txt
- src/globalcommands.cpp
- src/monitormanager.cpp
- src/monitormanager.h
- src/runtimeconverter.h
- tests/test_global_commands.py
- tests/test_monitor.py
This introduces a new converter class for the parsing of descriptions of
objects, e.g. Monitors, Tags, Clients. So far, only the converter for
Monitor* is implemented. If a command gets a monitor as a parameter, we
can now use ArgParse which internally uses the Converter class.
This new converter is used in the commands remove_monitor and tag_status
and their test cases have slightly been adjusted and extended.
> Add converter for objects such as Monitor

- src/clientmanager.cpp
- src/clientmanager.h
- src/command.cpp
- src/globalcommands.cpp
- src/globalcommands.h
- src/layout.cpp
- src/layout.h
- src/main.cpp
- src/monitormanager.cpp
- src/monitormanager.h
- src/mousemanager.cpp
- src/runtimeconverter.h
- tests/test_clients.py
- tests/test_global_commands.py
- tests/test_meta_commands.py
This implements RunTimeConverter for Client* and uses it in the commands
jumpto and bring which are moved to GlobalCommands.
Since there are multiple variables and functions called 'complete',
RunTimeConverter::complete is renamed to RunTimeConverter::completeEntries
to make the variable names a bit more unique.
The test cases with error handling are slightly extended and moved to
test_global_commands.py, but the existing 'positive' test cases for
bring and jumpto are still in test_clients and test_layout in order to
keep the diff small.
> Run-Time Converter for Client*

- src/monitormanager.cpp
- src/monitormanager.h
Change it to void, nobody uses the returned string.
> Remove unused lock_number_change return value

- NEWS
- doc/herbstluftwm.txt
- src/monitormanager.cpp
- src/settings.h
- tests/test_monitor.py
- tests/test_settings.py
The lock counter was always used as a non-negative integer and should
also be such on the type level. In the original settings code, all
integers where signed, but now it is finally updated.
Also it is not necessary anymore to call lock_number_changed() manually,
because this happens automatically through signals.
Both changes are tested by the new test cases for lock/unlock.
> Make setting monitors_locked an unsigned long

- src/types.cpp
- src/types.h
- tests/test_types.py
In the Converter for int and unsigned long, the parser now checks that
the entire input string is processed and no unparsable suffix is left at
the end.
This fixes #944.
> Converter for integers checks entire input string

- tests/test_herbstclient.py
In the case of hc_quiet, herbstclient was invoked with one parameter
"--quiet true" instead of with two parameters "--quiet" and "true".
> Fix herbstclient test case

- ipc-client/main.c
- tests/test_herbstclient.py
This extends the tests for most command line flags of the herbstclient
command. Also, herbstclient now prints an error message if too few
parameters are passed.
> Test herbstclient command line parsing

- NEWS
- doc/herbstluftwm.txt
- src/ewmh.cpp
- src/ewmh.h
- src/main.cpp
- src/root.h
- src/xmainloop.cpp
- src/xmainloop.h
- tests/test_herbstluftwm.py
Herbstluftwm now uses the ICCCM-specified way of checking whether there
is an existing window manager, namely by checking the ownership
particular 'selection'. The owner of this selection is the active window
manager. This change introduces the new features:
1. herbstluftwm does not start if the selection is already owned
2. if herbstluftwm is started with --replace, try to become the
owner of the selection
3. if herbstluftwm looses the ownership, then quit, because there is
some other window manager booting up.
In the test case, we only check that herbstluftwm can replace itself,
but I've tested it locally and the replacement works (forth and back)
with xfwm4, openbox, fvwm2, pekwm.
This change also adds a test case for the 'quit' command because it is
essentially half the test of …
> Option --replace to replace existing window manager

- src/monitormanager.cpp
- tests/test_monitor.py
The manpage says:
cycle_monitor [DELTA]
Cycles monitor focused by DELTA.  DELTA defaults to 1.
but after 28ea7f66ac9a889827f61206cdbc0743dd2e63c5, `hc cycle_monitor` says:
cycle_monitor: Expected one argument, but got only 0 arguments.
cycle_monitor: not enough arguments
because in #1200, it was accidentally marked as mandatory rather than optional.
> cycle_monitor: Make argument optional

- src/desktopwindow.cpp
- src/desktopwindow.h
- src/monitormanager.cpp
- src/xmainloop.cpp
- tests/test_stack.py
Instead of lowering desktop windows when they appear, manage desktop
windows in the global stack explicitly. Unfortunately, I did not find a
way to query the window stack. So for debugging and testing the output
of the `stack` command is extended by the desktop windows' winid and
window instance/class.
This solves an issue here where the Xfce's desktop window covered all
normal windows if I run `herbstluftwm --replace` in a running Xfce
session.
> Manage desktop windows in global stack

- cmake/debugflags.cmake
The issue is that we have to make casts from platform dependently sized
types such as size_t to platform independent types such as unsigned
long. Such a cast is sometimes useless and sometimes important,
depending on the platform, so we can't omit it.
This should make #1214 build again which contained such a "useless" cast.
> Remove -Wuseless-cast

- NEWS
- doc/herbstluftwm.txt
- src/client.cpp
- src/client.h
- src/globalcommands.cpp
- src/globalcommands.h
- src/main.cpp
- src/plainstack.h
- src/stack.cpp
- src/stack.h
- tests/test_completion.py
- tests/test_meta_commands.py
- tests/test_stack.py
Analogously to the 'raise' command, there should be a 'lower' command
that lowers a managed or unmanaged window in the stack. For example,
this can be used to manually lower a desktop window.
Fortunately, the test cases for 'raise' could either extended or easily
adapted to the 'lower' command.
> Add 'lower' command

- NEWS
- doc/herbstluftwm.txt
- src/CMakeLists.txt
- src/entity.h
- src/root.cpp
- src/root.h
- src/typesdoc.cpp
- src/typesdoc.h
- tests/test_meta_commands.py
- tests/test_types.py
This extends the object tree to also contain meta-information on the
available types. In order to keep the diff small, only the most basic
types are included.
The table defining the names of the types has not been used really (only
in the 'help' command so far). To make the names more uniform, I have
adjusted the names such that they match to the type argument of the
`new_attr` command (in the long run, `new_attr` should of course work
for all entries of the Types enum).
Since the objects essentially consist of documentation, there is not
much to test.
> New objects for types documentation

- doc/CMakeLists.txt
In the commit 59e175a68c81e53b0291c1e5d1ed1cee9ce978f6 (#1166)
I accidentally removed the dependency of the man page on the
asciidoc source file (doc/herbstluftwm.txt). This resulted in the man
page not being updated after changing doc/herbstluftwm.txt.
> Man page generation: add dependency on source txt

- src/CMakeLists.txt
- src/argparse.h
- src/client.h
- src/converter.cpp
- src/converter.h
- src/either.h
- src/finite.h
- src/fixprecdec.h
- src/font.h
- src/framedata.h
- src/frametree.h
- src/keycombo.h
- src/layout.h
- src/metacommands.h
- src/object.h
- src/rectangle.h
- src/regexstr.h
- src/rules.h
- src/runtimeconverter.h
- src/watchers.h
- src/x11-types.h
The types.h file mainly contains the Converter definition, and has
nothing to do with the Type enum (which is defined in entity.h). Thus, I
think it is more appropriate to call the file converter.h.
> Rename types.h (and .cpp) -> converter.h (and .cpp)

- share/herbstluftwm.desktop
As noticed by @Barbarossa93 in #599, this isn't the default although
the default autostart does `unlock`
> Start --locked from the .desktop file

- doc/gendoc.py
- tests/test_doc.py
Formerly, the doc/gendoc.py keept the comment tokens in the token tree.
This resulted in a comment being treated as the function body of a
function definition and hence some of the documentation was missed.
Also, this was not noticed because the classname2examplepath array was
not extended in test_doc.py. The present change fixes the main issue and
the test case, and even makes it a bit stricter.
> Fix doc/gendoc.py extractor to strip comments

- src/globalcommands.cpp
- src/globalcommands.h
- src/main.cpp
- src/monitor.cpp
- src/monitor.h
- src/monitormanager.cpp
- src/monitormanager.h
- src/tagmanager.cpp
- tests/test_monitor.py
Just like use and use_index, the 'use_previous' command fits well into
GlobalCommands. There were already some tests in test_monitor.py and
I've extended them slightly (and left them in test_monitor.py).
> Migrate the use_previous command to ArgParse

- src/command.cpp
- src/completion.cpp
- src/utils.cpp
- src/utils.h
- tests/test_completion.py
- tests/test_keybind.py
- tests/test_monitor.py
In the objects of the Completion class, the shellOutput_ member was not
used at all, and so the completion results were not escaped correctly.
Now, the results are escaped and while at it, the posix_escape()
function is converted to C++. This makes the implementation much simpler
and it even fixes a memory leak in command.cpp (prefix_escaped is never
free'd).
A new special case in the posix_escape() function is the empty string,
which is now escaped correctly (before, zsh just added a space to the
command line, which of course did not have any effect).
In the tests, there is a new case for the empty string, and the escaping
of the other characters is now tested for the commands 'use' and 'move'
which still use the old command completion but will soon be migrated
(for 'use', see #1224).
> Use posix escaping in Completion objects

- src/monitormanager.cpp
- tests/test_completion.py
The '0' was listed multiple times in the completion of the
'move_monitor' command. The issue was a wrong completion in the
EmptyOrInt class.
The new test case checks that there is only one '0' in the completion
list. In particular, this test ensures that the completions of multiple
optional arguments (such as in 'move_monitor') do not overlap.
> Fix completion in EmptyOrInt

- src/frametree.cpp
- src/tagmanager.cpp
- src/tagmanager.h
This extracts the Converter for HSTag* out of the PR (#1224) since
multiple new PRs require this.
> Run-Time Converter for HSTag*

- src/decoration.cpp
This fixes an issue (#1235) which consisted of hlwm hanging because of a
loop between hlwm and the reaper application (reaper.fm).
Apparently, the issue is that `XA_WM_NORMAL_HINTS` is updated by the
reaper window, and this causes the tiling layout to be re-computed,
which results in a ConfigureNotify sent to the window. This event seems
to make reaper set `XA_WM_NORMAL_HINTS` again and so the whole process
starts again.
The solution is to only send the ConfigureNotify if the geometry really
changed. I don't know how to write a test case for it, but any test case
more or less should check that this still sends enough ConfigureNotify
events as requested by ICCCM (section 4.1.5.).
> Only resend ConfigureNotify on geometry change

- python/herbstluftwm/types.py
- src/client.cpp
- src/client.h
- src/decoration.cpp
- tests/test_mousebind.py
Instead of deciding in Decoration when to send a configure, just
remember the last configure event in every client so we know directly
whether it is worth sending a new configure event or not.
This fixes the bug #1239 where moving a client with the mouse did not
send the configure event when the mouse dragging was over. (This caused
the menus in Qt applications to be positioned wrong.). The bug was
originally introduced by #1236, thanks to @tiosgz for reporting it!
For easier testing, this remembered window geometry is exposed via the
attribute system. To simplify writing tests for it, there is a new type
'Rectangle' in the python bindings.
> Remember last reported geometry in client directly

- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/decoration.cpp
- src/xmainloop.cpp
Depending on the context, it is mandatory to send back a configure
request, even if the window geometry did not change.
This fixes the issue that gnome-terminal and xfce4-terminal are blank on
start up, because they are waiting for the ConfigureNotify.
The bug was introduced by #1240 which is part of a sequence of changes
regarding issue #1235. The present change is just a quick fix, in the
long run this should be solved more elegantly.
> Always reply to a ConfigureRequest with ConfigureNotify

- tests/test_rules.py
Another test case that the smart placement really uses the decoration's
geometry (i.e. 'outer geometry') for the smart placement algorithm. I've
nearly introduced an issue related to this in another change, so it is
good to have it tested explicitly.
> Test that smart placement uses the decoration

- src/command.cpp
- src/frametree.cpp
- src/frametree.h
- src/globalcommands.cpp
- src/globalcommands.h
- src/main.cpp
- src/tagmanager.cpp
- src/tagmanager.h
- tests/test_global_commands.py
- tests/test_layout.py
Since focus_nth is just a convenience setting for
tags.focus.tiling.focused_frame.selection it better fits in
GlobalCommands. I've moved the existing test case to the other python
file and added a few more test cases. Also, the completion now
explicitly mentions '0' and '-1' for selecting the first and last window
in a frame.
This requires access to tags.focus which I thus had to make public in
TagManager.
> Migrate focus_nth to ArgParse

- src/tagmanager.cpp
- tests/test_completion.py
- tests/test_global_commands.py
When migrating the 'move_index' command in a5bdb0d45 (#1227) I forgot to
parse the --skip-visible flag. This brings the flag back and extends the
test cases of 'use_index' to also test 'move_index'.
While at it, I've also added the suggestions "-1" and "+1" for the index
argument (as it already exists for 'use_index'). This now needs an exception in
the automated completion tests (similarly to 'use_index')
This fixes #1256, thanks to @gravndal for reporting this issue!
> Parse --skip-visible in move_index command

- src/command.cpp
Remove the completion code for those commands that have been converted to
Completion objects or ArgParse.
This closes #1246.
> Remove old and unused command completion code

- src/client.cpp
- src/client.h
- src/command.cpp
- src/globalcommands.cpp
- src/globalcommands.h
- src/main.cpp
- tests/test_clients.py
The usual migration commit: use ArgParse for argument parsing and
command line completions, add tests for it, remove the old
implementation and completion code.
> Migrate 'close' command to ArgParse

- NEWS
- doc/herbstluftwm.txt
- src/command.cpp
- src/frametree.cpp
- src/frametree.h
- src/main.cpp
- src/tag.cpp
- src/tag.h
- tests/test_layout.py
If the floating layer is focused, 'cycle' should traverse through the
clients in there. While at it, I've migrated the command to ArgParse and
moved it to HSTag. As usual, there are some new test cases.
Still, this only cycles through the windows explicitly marked as
floating, which is maybe odd when switching the entire tag to floating
(which should be fixed in the long run, see issue #948).
> Make 'cycle' work for the floating layer

- tests/conftest.py
Sometimes the CI fails because the shutdown takes too long.
Thus, a slightly longer timeout might be reasonable. Moreover, the
shutdown of the HlwmBridge is now in parallel, so all processes are
sent the term signal simultaneously, so in sum, this might even speed up
the shut down phase of test cases with clients.
> tests: Relax timeouts for shut down a bit

- src/main.cpp
- src/tagmanager.cpp
- src/tagmanager.h
- tests/test_tags.py
This migrates 'add' to ArgParse and adds two more test cases. I didn't
remove the "add" from the command.cpp to avoid another merge commit.
The two main tables from command.cpp will be removed soon, anyway.
> Migrate 'add' command

- src/command.cpp
- src/command.h
- tests/test_completion.py
With the completion code from all commands migrated, most of the code in
command.cpp is now obsolete. There is still a bit of the char**-based code
which needs to be reorganized until we get rid of the old command
interface entirely.
The new tests verify that the exit code of the completion of `spawn` and
`wmexec` still are correct.
> Remove old completion code from command.cpp

- MIGRATION
- NEWS
- src/client.cpp
- src/client.h
- tests/test_mousebind.py
- tests/test_rules.py
I think the latter name is more self-explanatory and is not specific to
the internals of the X11 protocol.
> Rename 'geometry_reported' to 'content_geometry'

- HACKING
- ci/build.py
- tox.ini
Not sure if 3.6 is really used in "current" distributions anymore? At
least the CI is using 3.8. Also adjust the description in HACKING to be
more generic, this is not an Arch specific problem.
> tox: Switch default Python env to 38

- NEWS
- doc/herbstluftwm.txt
- src/argparse.cpp
- src/argparse.h
- src/command.cpp
- src/completion.cpp
- src/completion.h
- src/globalcommands.cpp
- src/globalcommands.h
- src/layout.h
- src/main.cpp
- tests/test_global_commands.py
For the new command 'list_clients' the main challenge was to extend
ArgParse by command line flags that take arguments. To make the
completion work, I also had to extend the completion objects by a
'prepend' string that is prepended to every completion result.
This implements the main feature request of #831 and also includes the
functionality of the rejected PR #1249.
> New command 'list_clients'

- NEWS
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/floating.cpp
- src/monitor.cpp
- src/mousedraghandler.cpp
- src/rectangle.h
- src/xmainloop.cpp
- tests/test_clients.py
- tests/test_monitor.py
- tests/test_mousebind.py
- tests/test_tags.py
Add a new attribute to access and write the floating geometry of a
client. In order to keep the diff small, I kept the name of the C++
variable in the source code, even though '...geometry' is more
appropriate.
In the diff, I replaced member write-access with a preparation of the
new Rectangle and a single write. This is inevitable anyway because the
operators * and -> of Attribute_<> only return const references (as they
should). Read-only member access is no problem; here, I only had to
replace '.' with '->'.
There is not much necessity to test the attribute itself, but instead,
it serves as a tool to test other features of hlwm (e.g. the pad and the
monitor geometry).
> Add client attribute 'floating_geometry'

- src/argparse.cpp
- src/clientmanager.cpp
- src/command.cpp
- src/command.h
- src/commandio.cpp
- src/commandio.h
- src/frametree.cpp
- src/globalcommands.cpp
- src/hlwmcommon.cpp
- src/hlwmcommon.h
- src/ipc-server.cpp
- src/ipc-server.h
- src/keymanager.cpp
- src/main.cpp
- src/metacommands.cpp
- src/monitor.cpp
- src/monitormanager.cpp
- src/mousemanager.cpp
- src/object.cpp
- src/rulemanager.cpp
- src/rules.cpp
- src/settings.cpp
- src/tag.cpp
- src/tagmanager.cpp
- src/xmainloop.cpp
- src/xmainloop.h
- tests/test_meta_commands.py
In the command system, the 'Output' parameter now also carries an error
channel and the command name (in addition to the standard output
channel). This is accomplished with a new class OutputChannels in
commandio.h (and Output = OutputChannels&).
So far, this only affects the command system, but not the IPC interface,
which thus simply concatenates the two output channels in the reply to
'herbstclient'.
Thus, we can now print error messages to this dedicated channel and have
the error message prefixed with the command name automatically. Most of
the diff consists of migrating the error message printing to the new
perror(), which does the prefixing.
As a bonus, CallOrComplete does not need the command name anymore.
Also, HlwmCommon::callCommand() was only used in XMainLoop, so I have
used …
> Support error output channel internally

- NEWS
- python/herbstluftwm/__init__.py
- python/herbstluftwm/types.py
- tests/test_clients.py
- tests/test_global_commands.py
- tests/test_layout.py
- tests/test_monitor.py
- tests/test_mousebind.py
- tests/test_panels.py
- tests/test_python_binds.py
- tests/test_rules.py
- tests/test_stack.py
- tests/test_tags.py
- tests/test_types.py
- tests/test_watchers.py
In the python bindings, automatically convert the attribute values from
(resp. to) their corresponding python types when writing (resp. reading)
attributes.
This requires touching (but fortunately simplifying) a lot of assertions
in the test cases. Now, working with the contents of hlwm.attr should
feel as if one had the hlwm attributes available as python variables.
A few new test cases at the end of test_python_binds.py illustrate the
usage for all types that are available at the moment.
> Auto-convert attributes to/from python types

- share/panel.sh
In panel.sh, we extract the current colors from the hlwm settings.
However, the latter possibly have alpha-values (some even have in the
default autostart). So, we need to remove these alpha-values, turning the
rgba-format into rgb.
This fixes #1282
> Remove alpha-value from colors in panel.sh

- MIGRATION
- NEWS
- ipc-client/ipc-client.c
- ipc-client/ipc-client.h
- ipc-client/main.c
- python/herbstluftwm/__init__.py
- src/clientmanager.cpp
- src/frametree.cpp
- src/globalcommands.cpp
- src/ipc-protocol.h
- src/ipc-server.cpp
- src/keymanager.cpp
- src/metacommands.cpp
- src/mousemanager.cpp
- src/object.cpp
- src/rulemanager.cpp
- src/rules.cpp
- src/tag.cpp
- src/tagmanager.cpp
- tests/conftest.py
- tests/test_doc.py
- tests/test_herbstclient.py
- tests/test_keybind.py
- tests/test_layout.py
- tests/test_load.py
- tests/test_meta_commands.py
- tests/test_rules.py
This makes the ipc protocol and herbstclient support the error channel.
In order to make herbstclient compatible with old herbstluftwm ipc
server implementations, the error channel support is indicated by an
atom on hlwm's ipc server window (which is so far only used for the hook
system). Conversely, an old herbstclient version should also work more
or less with the new herbstluftwm ipc server: it simply ignores the
error channel.
Due to this change, a few more missing `output.perror()` calls surfaced,
affecting implementation and test cases.
In order to test the new herbstclient, the test suite features a
minimalist ipc server implementation which can be used to simulate wrong
behaviour and thus to stress the error handling in the client.
> Extend IPC protocol by error channel

- src/command.cpp
- tests/test_herbstluftwm.py
This is yet another error message that belongs to the new error channel.
> Write 'command not found' to the error channel

- src/argparse.cpp
- src/metacommands.cpp
- tests/test_meta_commands.py
If ArgParse::parsingAllFails() notices too many arguments, print a
message to the error channel. This affects e.g. 'hc help'.
> Print error message on too many arguments

- src/metacommands.cpp
- tests/test_meta_commands.py
Thanks to the coverage reported, I've noticed that the function
parse_and_compare<unsigned long> was not used at all. The mistake was
introduced in 698dcd74ddbe96e96429c5ce874b2d099fd8c3cd.
It is hard to write a test case for it, but I've added some test case of
other yet non-covered parts of the error handling and completion of
'compare'.
> Use correct comparison function in 'complete'

- src/metacommands.cpp
- tests/test_meta_commands.py
Main purpose of this change is to have a test case for the 'substitute'
completion. While writing the test, I've noticed that the placeholder
should only be inserted if the nested command still expects an argument,
which was incorporated easily.
> Refine completion of the 'substitute' command

- src/metacommands.cpp
- tests/test_meta_commands.py
This adds a couple of more tests for the meta commands object_tree,
new_attr, and sprintf. This mainly concerns error handling and
completion. This should improve the test coverage.
> Test for commands: object_tree, new_attr, sprintf

- tests/test_rules.py
This was tested for apply_rules already, but not for apply_tmp_rule,
which was easily added.
> Test apply_tmp_rules invalid client error

- src/utils.cpp
- src/utils.h
posix_sh_compress_inplace seems unused, posix_sh_escape on the other
hand is not.
> utils: Remove unused method

- tests/conftest.py
- tests/test_herbstclient.py
Test the -0 command line option of herbstclient. Unfortunately, this
still uses tab characters to separate the arguments.
To avoid the race condition when starting herbstclient --idle, I'm
making the HcIdle implementation in conftest.py capable of -0 and simply
use this in the new test cases.
> Test herbstclient -0 --idle

- src/main.cpp
- tests/test_spawn.py
Print the correct command name if exec fails (instead of the memory
address). The new test case verifies that this does not happen again.
This fixes #1302.
> Fix exec error message in spawn command

- src/floating.cpp
- src/rectangle.cpp
This fixes a compilation error on Gentoo with GCC 11[1], complaining
about an undefined std::numeric_limits in the namespace std. According
to cppreference std::numeric_limits requires including <limits>. This
adds the include to floating.cpp, where the error occurred, and also to
rectangle.cpp (which also uses std::numeric_limits but did not have the
include).
[1] https://bugs.gentoo.org/787848
> Include <limits> for std::numeric_limits

- tests/test_herbstclient.py
This tries to fix a race condition in the herbstclient tests with the
test suite IpcServer class that happened quite regurarly in the CI:
according to the log the herbstclient did not boot up (in time).
Instead of waiting for a certain amount of seconds, the IpcServer class
now waits for a certain number of X11 events for the herbstclient to
show up. The downside is that on failure, the CI hangs until the CI
itself times out, but hopefully this does not happen at all.
> Wait passively for hc in test suite ipc server

- tests/test_types.py
This only adds a small test case that an alpha value '09' is not
misinterpreted as an invalid octal number.
> Another small test case for color parsing

- src/tag.cpp
- tests/test_floating.py
The 'resize' command shrinks the client if the monitor edge is reached.
The present change adds test cases for shrinking and also adds an error
message if the client can not be shrunk any further.
> Test shrinking of floating clients via 'resize'

- MIGRATION
- NEWS
- doc/herbstluftwm.txt
- src/rulemanager.cpp
- src/rules.cpp
- src/rules.h
- tests/test_keybind.py
- tests/test_rules.py
When creating a new rule (via the `rule` or `apply_tmp_rule` command),
then a erroneous argument to a rule consequence (e.g. an invalid regular
expression) will be reported directly and will make the rule creation
fail. This helps finding mistakes earlier. Before, herbstluftwm printed
an error message during rule usage to its stderr, which is usually not
monitored by anybody.
On the negative side, this makes it now impossible to use 'toggle' in
boolean rule consequences. But I assume nobody uses this anyway, because
the result is of course highly unpredictable. Also, no rule consequence
can fail at run time at the moment, which produces dead code in
Rule::evaluate(), but I'm keeping this to be on the safe side.
As a positive side-effect, the redundancy in the applier implementation
in the …
> Report rule consequence errors during rule creation

- doc/herbstluftwm.txt
- python/herbstluftwm/types.py
- tests/test_rules.py
This documents and tests the interaction of the floatplacement and
floating_geometry rule consequences. Since 'floatplacement' is not
applied by 'apply_rules' / 'apply_tmp_rules', the test case only
mentions the 'rule' command (also I've fixed a typo along the way).
For the readability in the tests, I've introduced a Point datastructure
to herbstluftwm's python bindings.
> Doc on rule floatplacement vs floating_geometry

- NEWS
- doc/herbstluftwm.txt
- share/autostart
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/tag.cpp
- src/tag.h
- tests/test_clients.py
- tests/test_completion.py
- tests/test_stack.py
- www/faq.txt
This adds client aliases for accessing the longest and the most recently
minimized client, and thus provides a native way to un-minimize clients
with key bindings (either in a lifo or fifo way). Thus, this also works
when minimizing clients via the panel and thus is more universal than
restricting to the unminimize.sh script (which was written for the lifo
unminimize).
With the new feature, we do not need the complicated binding for
unminimizing all clients anymore and we can move it to the faq (and
simplify it a bit).
This solves another feature request raised in the discussion of #1014.
> Client alias 'longest-minimized' and 'last-minimized'

- tests/test_monitor.py
This adds a test that monitor names appear and disappear in the output
of the list_monitors command.
> Test that list_monitors mentions monitor names

- tests/test_monitor.py
This tests the (successful and unsuccessful) parsing of addressing
monitors via directions.
> Test directional monitor references

- NEWS
- doc/herbstluftwm.txt
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/clientmanager.h
- src/ewmh.cpp
- src/ewmh.h
- src/tag.cpp
- src/xconnection.cpp
- src/xconnection.h
- tests/test_clients.py
The purpose of this change is to indicate a clients effective floating
state via X11 properties to make use of it in rules of X11 compositors.
The change happens in two steps: The first step is a new read-only
attribute `floating_effectively` which combines the client's single
window floating state with its tag's floating state. This attribute is
tested semantically. The second step is simply a signal connection that
sets or removes the X11 properties HLWM_FLOATING_WINDOW and
HLWM_TILING_WINDOW, depending on the value of `floating_effectively`.
This closes #1172.
> Set X11 property for client's floating state

- NEWS
- src/client.cpp
- src/client.h
- src/clientmanager.cpp
- src/xmainloop.cpp
- tests/test_floating.py
If the size hints of a client change, then its floating geometry must be
updated. Also, this must happen even if the client is not floated at the
moment. To accomplish the latter, the applysizehints() function is
extended by an optional `force` parameter. The new test case verifies
both the floating and non-floating case.
This fixes #1322.
> Update floating geometry if size hints change

- NEWS
- python/herbstluftwm/types.py
- src/client.cpp
- src/client.h
- tests/test_theme.py
This adds a new read-only client attribute `decoration_geometry` that I
would have liked to have for many test cases.
> Add client attribute 'decoration_geometry'

- HACKING
- INSTALL
- README.asciidoc
- doc/herbstclient.txt
- doc/herbstluftwm.txt
- www/index.txt
Due to the recent policies on freenode, we move our irc channel to
libera.chat. Some irc channels on freenode mentioning 'libera.chat' in
their topic were closed forcefully.
> Move IRC channel to Libera

- src/decoration.cpp
- src/decoration.h
Encapsulate the text drawing in a separate function, the existing test
cases should cover most of it.
> Move text drawing to own function

- src/command.cpp
- src/command.h
- src/main.cpp
- tests/test_herbstluftwm.py
The commands spawn and wmexec were the last that used the old char**
argv interface. For 'spawn', test cases existed already, for 'wmexec',
I've added some more test cases.
> Migrate spawn and wmexec to Input and add tests

- src/decoration.cpp
- src/decoration.h
- src/fontdata.cpp
- src/fontdata.h
- tests/test_decorations.py
Shorten a client's title such that it is at most as wide as the window
content, i.e. such that it does not reach into window border.
The new tests verify this by looking for the leftmost and rightmost
pixels belonging to the title. Unfortunately, proper utf8 characters
work in the test suite only with xft fonts. But in a manual xephyr
session, the plain X fonts also work with utf8 characters.
> Shorten window title to decoration width

- NEWS
- src/CMakeLists.txt
- src/autostart.cpp
- src/autostart.h
- src/main.cpp
- src/root.cpp
- src/root.h
- src/xmainloop.cpp
- src/xmainloop.h
- tests/test_autostart.py
- tests/test_herbstluftwm.py
This adds an autostart object which allows modifying the custom
autostart path at run time and also helps querying information about the
last invoked autostart run (pid, status, running).
This closes #762.
> Add an autostart object

- NEWS
- src/client.cpp
- src/client.h
- src/decoration.cpp
- src/decoration.h
- src/ewmh.cpp
- src/layout.cpp
- src/layout.h
- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/mousemanager.cpp
- src/mousemanager.h
- src/xmainloop.cpp
When the mouse cursor is at a client's window border, the cursor shape
now changes to indicate the direction in which the window resizes.
Also, I've updated the resize code itself to allow resizing where the
width or height is fixed and the client is resized only into one
dimension.
Unfortunately, the cursor preview isn't entirely correct for tiled
windows. Also does not seem to be possible to query the cursor shape in
test cases.
This closes #1138.
> Update cursor shape and resize accordingly

- NEWS
- src/autostart.cpp
- src/main.cpp
- src/utils.cpp
- src/utils.h
- src/xconnection.cpp
- tests/test_herbstluftwm.py
- tests/test_spawn.py
This encapsulates the spawning of new processes in a utility function
that either returns the pid of the child process or a error message.
Thus, the 'spawn' command now prints a meaningful error message if the
exec failed.
Formerly, we manually closed the socket for the X11 connection on every
fork. Now, the X11 socket is marked as 'CLOEXEC' (close on exec), if it
hasn't been already by XOpenDisplay(). This eliminates another instance
of the global g_display variable.
Unfortunately, I don't know how to really test the low level error
messages for pipe() and fork(). But there are test cases for the other
error messages for 'spawn' and also a new test case for 'wmexec'.
In the long run, the spawnProcess() function should also be used in the
autostart invocation in the 'reload' command to …
> spawn: Print error message on exec failure

- tests/conftest.py
- tests/test_clients.py
- tests/test_ewmh.py
- tests/test_global_commands.py
- tests/test_herbstclient.py
- tests/test_herbstluftwm.py
- tests/test_keybind.py
- tests/test_tags.py
This unifies the timeout in the test cases when waiting for a child
process to terminate.
> tests: increase process shutdown timeout

- tests/conftest.py
- tests/test_autostart.py
- tests/test_herbstclient.py
When using subprocess.Popen() and piping stdout or stderr, the pipe
needs to be closed on shutdown.
For the present change, I've grep'ed for all uses of subprocess.Popen()
and added the necessary close() invocations. In one occasion, I could
simply replace subprocess.Popen() / communicate() with subprocess.run()
which already takes care of this.
Unclosed file descriptors and similar issues are reported by passing
`-Wdefault` to pytest.
Reported-by: Florian Schmaus <flo@geekplace.eu>
> tests: Close stdout/stderr after subprocess.Popen

- www/Makefile
- www/compose.py
- www/contrib.txt
This adds a `contrib.txt` file to the `www` directory and solves #1340
I decided to add the new section as a new tab. I included instructions on how to add new contributions and I added some contributions I found at r/herbstluftwm. I have to make it clear: I didn't ask  permission from the authors to include their contributions on the webpage, I just assumed that I could do it since they had already shared it on reddit and they're using free licences. Of course, each contribution has the username of whoever shared it and (if apply) a link to their repo.
I also changed the `compose.py` files so the new section can be compiled by asciidoc.
> Add an "Users contributions" section on the webpage

- tests/conftest.py
Recently, a timeout exception in the CI was repeatedly thrown during the
shutdown of the test_ipc_reply_with_error_channel test case, causing
annoying failures of the CI. One can reliably reproduce the timeout by
increasing the repeat parameter of the test case.
The fix is to send sigkill if the process did not shut down after the
sigterm. Of course, this implicitly doubles the timeout. Anyway, this
should solve the issue for us.
> tests: Fix Xvfb shutdown timeout

- NEWS
- python/herbstluftwm/types.py
- src/decoration.cpp
- src/decoration.h
- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/mousemanager.cpp
- src/mousemanager.h
- src/xmainloop.cpp
- tests/test_mousebind.py
This implements a feature which was already indicated by the cursor shape:
resizing frames in both x and y direction. For this, it was necessary to
entirely change the drag handler for resizing frames.
As a little bonus, the special cursor shape persists during the drag.
The new test case essentially checks that resizing in both dimensions
works as expected. The existing testcase for 1-dimensional resize
could be simplified a lot using new attributes and the convenience
functions in the python bindings.
> Resize frames in both dimensions

- NEWS
- share/autostart
- src/client.cpp
- src/client.h
- src/decoration.cpp
- src/stack.cpp
- src/xmainloop.cpp
- tests/test_clients.py
This adds a client attribute 'decorated' that adjusts whether a client
has a window decoration frame. Changing the option reparents the window
either to the root or to the decoration window.
This should make it easier to work with shaped windows and to solve
issues with freesync (#1347).
> Attribute to disable window decorations

- doc/gendoc.py
- tests/test_doc.py
This fixes a wrongly nested if-statement in gendoc.py which caused the
doc string of Attributes to be hidden if they were member-initialized
(during the class definition). This affects the doc string of all theme
attributes.
The new test case checks that (and failed before the present change to
gendoc.py).
> Fix doc for member-initialized attributes

- NEWS
- doc/herbstluftwm.txt
- share/autostart
- src/client.cpp
- src/client.h
- src/decoration.cpp
- src/decoration.h
- src/layout.cpp
- src/monitor.cpp
- src/rectangle.h
- src/settings.cpp
- src/settings.h
- src/tilingresult.h
- src/xmainloop.cpp
- tests/conftest.py
- tests/test_decorations.py
This draws the hidden windows in max layout as tabs if the setting
tabbed_max is set (which is the default).
This directly closes #1299 and also implements a suggestion mentioned in
#1097 and in various other places throughout the years.
> Draw tabs in max layout

- src/monitor.cpp
- tests/conftest.py
- tests/test_stack.py
Correctly raise focused fullscreen windows above unmanaged windows (such
as panels). Beside the fix, this also contains a test case.
This closes #1383.
> Raise undecorated fullscreen windows above panels

- src/xconnection.cpp
- src/xconnection.h
- src/xmainloop.cpp
- src/xmainloop.h
- tests/test_x11.py
Usually, clients should request a focus change via an EWMH request,
which the WM can then respect or ignore. Some clients however just
change the input focus themselves (i.e. they change the window where
keyboard events are sent to), e.g. via XSetInputFocus().
Examples are `xdotool windowfocus` or `emacsclient -n $filename`.
The only way to handle these input focus changes is to update hlwm's
state to match the new focus. I am not entirely confident in the code
handling it, but it seems to update the clients.focus object accordingly
(see the new test case) and it does not trigger any endless loop (which
would happen without the XCheckMaskEvent()).
I assume that this fixes the issue #33.
> React to focus stealing via XSetInputFocus

- src/decoration.cpp
Draw the tab title earlier, such that letters reaching below the baseline get
covered by the tab border if there is not enough space.
This fixes #1388.
> Draw title of tabbed windows before horizontal border

- .github/workflows/hlwm.yml
The 'build doc' regularly fails in the CI with the message:
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam
navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0
"/etc/asciidoc/docbook-xsl/manpage.xsl"
"/home/runner/work/herbstluftwm/herbstluftwm/build-1017/doc/herbstclient.xml"
returned non-zero exit status 6
With this change, I simply make 4 attempts, since it is probably not
worth the effort to investigate the actual issue of a2x/xsltproc.
> Try to work around CI failure of xsltproc

- NEWS
- doc/herbstluftwm.txt
- src/metacommands.cpp
- src/metacommands.h
- tests/test_completion.py
- tests/test_meta_commands.py
This adds two flags to foreach: --unique removes duplicates (or more
precisely, aliases) of objects and --recursive recurses into subobjects.
To ensure termination --recursive implicitly also uses --unique. The
recursion is done in a breadth-first way such that deeply nested objects
are visited later.
The main application for --unique is to avoid the duplicate
clients.focus and the main application of --recursive is to traverse all
frames in the tree layout.
> Extend foreach command by --unique and --recursive

- NEWS
- doc/gendoc.py
- src/decoration.cpp
- src/decoration.h
- src/font.cpp
- src/font.h
- src/theme.cpp
- src/theme.h
- tests/test_decorations.py
- tests/test_doc.py
This adds a new attribute title_align that configures the horizontal
alignment of the window title within the title bar, respectively tab.
This was requested in #1097.
> Make title alignment configurable

- python/setup.py
Similar to what was done in the [sampleproject repo](https://github.com/pypa/sampleproject/blob/main/setup.py).
Also capitalized starting of description.
> Remove remaining os.path usage in setup.py

- NEWS
- src/decoration.cpp
- src/settings.cpp
- src/settings.h
- src/utils.cpp
- src/utils.h
- tests/test_decorations.py
As requested in #1395, this adds an ellipsis, which is appended to the
window title if its too long for the available space. This requires that
we erase characters in the middle of a utf-8 string, and so we need to
take care of characters that amount to multiple bytes in the string.
This closes #1395.
> Add settings.ellipsis

- src/decoration.cpp
- tests/test_decorations.py
If the title was centered or right-aligned, the title sometimes moved
slightly. This was caused by the text area having slightly different
widths for active and inactive tabs. The present change fixes this and
adds a test case for it.
Unfortunately, the test case is quite time consuming (8 seconds here),
because it takes 3 * 2 = 6 screenshots, but I think it's worth the
effort.
> Let active and inactive tabs have same text width

- NEWS
- share/autostart
- src/client.cpp
- src/decoration.cpp
- src/theme.cpp
- src/theme.h
- tests/conftest.py
- tests/test_doc.py
- tests/test_theme.py
This makes it configurable when to show the title bar. So far, there are
four options that essentially depend on the number of tabs.
So far, I've used padding_top to add space for characters in the title
that reach below the baseline. Since the space below the baseline should
be present only when the title is shown, I've added a new setting
title_depth.
This new feature was requested multiple times on the IRC and in the
discussion of #1097 and #1388.
> Add attributes 'title_when' and 'title_depth'

- .github/workflows/hlwm.yml
- doc/CMakeLists.txt
- doc/herbstluftwm.txt
- doc/literal2emph.xsl
This patches the man page creation such that text formatted in fixed
font is recognizable in the man page. This is makes examples stand out
more in the man page.
On the technical side, the cmake file now does the two steps which are
normally done by a2x: first creating a docbook xml, and then
transforming the xml to a man page. By doing these steps manually, we
can now patch the intermediate xml file to our needs.
Maybe, this also helps us to see more error messages which were formerly
buried in a2x. In fact, the present change helped to discover two
broken links within the herbstluftwm man page, which I've fixed along
the way. Strictly speaking, we don't need the a2x binary anymore, but
since it comes with asciidoc anyway, I've left it as a dependency.
> Make fixed font visible in man page

- src/client.cpp
- src/client.h
- src/ewmh.cpp
- src/xconnection.cpp
- src/xconnection.h
- src/xmainloop.cpp
- tests/conftest.py
- tests/test_clients.py
This simplifies the handling of urgency handling and as a bonus, it
makes the urgency attribute writable.
The main idea behind this change is to separate the logic from the
communication with X11. One function (readWmHints) reads the urgency
hint from X11 to the attributes, and a signal propagates changes of the
attribute's value back to X11. The entire hlwm 'logic' only operates on
the urgency attribute (and so we can also grant the user write access to
it). This is similar to the focus change handling in #1403.
Also, this avoids a few X11 errors if a new client is already urgent.
Before this change, an urgent client triggered an early relayout, which
even led to the CI failure in #1399.
> Simplify urgency handling by using signals

- src/xmainloop.cpp
- tests/conftest.py
- tests/test_basic_events.py
- tests/test_mousebind.py
This implements the following fixes:
1. an unfocused window can now be mouse-resized without getting
focused.
2. mouse-resizing a tiled window with tabs now works also at the
decoration edge at unfocused tabs (i.e. if the second tab is
focused, then one can resize the window by dragging the top left
corner and without activating the first tab).
There are now test cases that verify both these fixes.
> Handle mouse clicks in correct order

- src/xmainloop.cpp
- tests/test_mousebind.py
When clicking a client's border, check it early whether the client can
be resized at all. If it can not be resized, then focus the client
instead, because this is what the (normal) cursor shape indicates.
This closes #1407, a bug introduced by PR #1404.
> Check early on click if client resize is possible

- src/client.cpp
- src/client.h
- src/theme.h
By making Theme::Type a separate enum class ThemeType, we can use
forward declaration and avoid, that theme.h is included in client.h.
> Avoid theme.h include in client.h

- NEWS
- share/autostart
- src/decoration.cpp
- src/either.h
- src/theme.cpp
- src/theme.h
- tests/test_decorations.py
- tests/test_doc.py
- tests/test_types.py
In order to distinguish unselected from selected tabs, this adds new
attributes for controlling tab appearance. Those attributes can also be
empty, which will cause the normal attributes to be used (as before);
this makes the change 100% backwards compatible.
This implements what has been requested during the discussion of #1388
and closes #1389.
> Add theme options for unselected tabs

- src/clientmanager.cpp
- tests/conftest.py
- tests/test_basic_events.py
In the MapNotify for an unmanaged window, manage_client() is called,
which should not call XMapWindow(), because the window is already
visible. When XMapWindow() was still called, this could trigger wrong
behaviour if a x11 client quickly maps and then unmaps the window,
because hlwm would then map the window again.
Concretely, this bug triggered an endless loop when pressing Alt in
pcmanfm (one should only test this in Xephyr, otherwise the session
hangs).
The new test case quickly maps and unmaps a window, and verifies that
hlwm does not try to map the window again.
> Do not map already visible unmanaged windows

- src/client.cpp
- tests/test_ewmh.py
This correctly puts the input focus to clients that exist before hlwm.
This is a bug that was brought to the surface by PR #1403, because now,
hlwm only calls XSetInputFocus() if the focus actually changes.
The solution now is: the decoration window is 'unmapped' if and only if
the client window itself is 'unmapped'. This is true already for all
clients that show up during the hlwm execution, but wasn't true for
clients existing before. With this property, making the client visible
(in Client::set_visible()) will actually set the client to the 'mapped'
state, triggering a MapNotify event, whose handler then calls
XSetInputFocus() if necessary.
> Fix input focus for preexisting clients

- src/xmainloop.cpp
- src/xmainloop.h
I think that this now solves the issue of the endless FocusIn event loop
triggered by #1386. However, I still do not know how to reproduce the
endless loop. In the present solution, I avoid that the handler of
FocusIn triggers further FocusIn or similar events (via the member
duringFocusIn_).
While at it, I've moved all calls to XSetInputFocus() to a custom
setInputFocus() function that possibly falls back to the WM_TAKE_FOCUS
method if the client requests so.
> Prevent endless focus stealing loop

- tests/conftest.py
By default, pytest has its assertion rewriting disabled for code outside of the
tests and conftest modules, to avoid testing different code than what runs in
production.
However, we have assertions in the herbstluftwm module, so it would be good to
benefit from rewriting there, too.
Docs: https://docs.pytest.org/en/latest/how-to/writing_plugins.html#assertion-rewriting
For a test such as:
def test_failing(hlwm):
hlwm.call("false")
This turns the output:
>       assert proc.returncode == 0
E       AssertionError
into output with additional assertion information:
>       assert proc.returncode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = CompletedProcess(args=['.../build/herbstclient', '-n', 'false'], returncode=1, stdout='', stderr='').returncode
Which will hopefully …
> tests: Register herbstluftwm module for assertion rewriting

- NEWS
- doc/herbstluftwm.txt
- share/autostart
- src/client.h
- src/rulemanager.cpp
- src/rules.cpp
- src/rules.h
- tests/test_rules.py
As requested in #1406, this introduces a new rule condition `fixedsize`
which checks whether minimum and maximum size of a window match.
The condition does not take a parameter, because otherwise, it looks as
if it was a rule consequence.
This closes #1406.
> Add 'fixedsize' rule condition

- share/panel.sh
I noticed the pids on my system getting quite big somewhat fast. With dual monitors, I had ≥ 4 forks/sec or ≥ 14400 forks/hour just from panel.sh.
While this is not a big issue, I hope you find these changes useful.
> panel.sh: Remove 2 forks/second per panel

- NEWS
- src/client.cpp
- src/monitor.cpp
- src/monitor.h
- src/mousedraghandler.cpp
- src/mousedraghandler.h
- src/mousemanager.cpp
- src/mousemanager.h
- src/root.cpp
- tests/test_mousebind.py
This allows that floating clients can be dragged between monitors. When
moving the dragged client to another monitor, the monitors are redrawn
multiple times, and one flicker might occur, but I think one can live
with that.
While at it, I also removed another odd behaviour: if a tag with
floating windows is moved from a big to a small monitor, then the
windows do not 'glue' in the bottom right corner anymore, because the
floating position is now fixed when the drag starts.
Both new features have their test case.
This closes #1415 and #1245.
> Drag floating clients between monitors

- src/monitormanager.cpp
- tests/test_monitor_detection.py
The monitor detection must remove duplicates in the list of detected
outputs, because a monitor might be mirrored to another one. However,
removing duplicates must still preserve the order, especially if there
are no duplicates at all -- most importantly because the 'primary'
monitor is at index 0.
In the X servers used in the test suite (Xephyr, Xvfb), we unfortunately
can't specify the outputs' position, so we use that Xephyr places
outputs next to each other and Xvfb places them all at (0,0).
Also, this introduces a test case for randr (only one monitor works
here, but it's better than nothing).
This fixes #1363.
> Preserve detected monitor order when deduplicating

- .github/workflows/hlwm.yml
- doc/CMakeLists.txt
- doc/patch-manpage-xml.py
This essentially reverts the cmake changes of f61211ad0f (#1396) and
instead injects the patch-manpage-xml.py via asciidoc's xmllint step.
The positive effect of this is that we do not need to know the path used
in ASCIIDOC_MANPAGE_XSL. Recently on arch linux, it was moved from
/etc/asciidoc/docbook-xsl/manpage.xsl
to
/usr/lib/python3.10/site-packages/asciidoc/resources/docbook-xsl/manpage.xsl
which of course depends on a lot of parameters (python version, etc).
Since I couldn't find a way to let asciidoc tell me the path, so having
the path a cmake parameter will presumably cause a lot of packaging
headache.
Instead, I noticed, that we could abuse the 'xmllint' step of the
asciidoc compilation to inject a tool that patches the man page xml.
As a side-effect, this changes make the …
> Use xmllint step of a2x for patching manpages

- src/decoration.cpp
Even though I'm not aware of any bad consequences of different visuals,
it might be cleaner to have the same 'Visual' structure in all windows
that are nested in the decoration window.
> Use same visual for all windows in the decoration

- NEWS
- ci/Dockerfile.ci-focal
- ci/Dockerfile.ci-trusty
- cmake/dependencies.cmake
- src/CMakeLists.txt
- src/decoration.cpp
- src/decoration.h
- src/ewmh.cpp
- src/ewmh.h
- src/framedecoration.cpp
- src/x11-types.cpp
- src/x11-types.h
- src/xconnection.cpp
- src/xconnection.h
- src/xmainloop.cpp
- src/xmainloop.h
- tests/test_x11.py
This fixes the color handling of rgba colors. The compositing of X11
expects the true transparency colors to be 'premultiplied' with the
alpha value. That is, a color r=g=b=80 with 50% alpha should have
r=g=b=40 (see also [1,2]).
This bug was still present in colors for both frame decorations and
normal decorations.
Due to this premultiplication, colors would appear darker if the
premultiplication was applied also in absence of a compositing manager
(aka compositor). Thus, this change also includes new code that detects
the presence and absence of a compositing manager at run time, using the
xfixes X11 extension library (which should be available on all systems
that have X11).
The new test cases essentially check that hlwm toggles this
premultiplication depending on whether a compositor …
> Premultiply colors with alpha if compositing

- .mergify.yml
Since mergify deprecates commit_message, we can hopefully recreate the
desired behaviour with commit_message_template: the commit message
should be the text in the PR body.
It took some attempts until I made it work. For instance, it is *not
enough* to set
commit_message_template: "{{ body }}"
I have tested the new setting in my personal fork, where the pull
request[1] had the desired message in the pr body. There are multiple
commits in this pr, but none of them show up in the message of the
squashed commit[2], as desired.
[1] https://github.com/t-wissmann/herbstluftwm/pull/10
[2] https://github.com/t-wissmann/herbstluftwm/commit/6cc99630adb61a93e941bfaced90f7311cf3653b
> Mergify: use commit_message_template

- share/panel.sh
I can't remember why I activated the silencing of stderr in
dd6436ad451ba351 but now it is causing trouble because it hides the
error message of the textwidth utility.
> Do not silence error channel of panel.sh main loop

- tests/test_decorations.py
This makes the test a bit more robust. For small fonts sizes, font
hinting affects more pixels and so counting pixels with the 'main' color
leads to more imprecise results.
> Increase font in test

- tests/conftest.py
Right before terminating herbstluftwm in the test suite, verify that
herbstclient is still working. Maybe, this helps with solving #1448.
> Test suite: ping before shutdown

- src/decoration.cpp
- src/decoration.h
- src/tag.cpp
- tests/test_clients.py
Before unmanaging and deleting a client, remove it from all tab bars of
the remaining clients. This fixes a crash triggered by the new test case
included in this change.
> Fix: Remove client from tab bars before unmanage

- .github/workflows/hlwm.yml
We need to run 'update' before installing the dependencies for the
documentation build. This should fix the current CI issue.
> CI: update pkg list before doc build

- .github/workflows/hlwm.yml
When multiple commits are pushed to the same PR, every still running
workflow of previous commits is now cancelled.
> Cancel outdated workflow runs

- NEWS
- src/framedecoration.cpp
- src/framedecoration.h
- src/frametree.cpp
- src/layout.cpp
- src/layout.h
- src/monitor.cpp
- src/monitor.h
- tests/test_layout.py
- tests/test_monitor.py
This adds new read-only attributes for accessing the content geometry of
frames (splits and leaves) and monitors.
There is not much to test here, so I've used both attributes in other
test cases.
While at it, I've also added documentation for the `index` attribute.
This closes #1462.
> Add content_geometry attribute to monitors and frames

- src/keycombo.cpp
- src/keycombo.h
- src/keymanager.cpp
- src/keymanager.h
- src/mousemanager.cpp
- src/root.cpp
- src/root.h
- src/xkeygrabber.cpp
- src/xkeygrabber.h
- src/xmainloop.cpp
This makes KeyManager independent of X and avoids some usages of the
global variable `g_display`.
In the MouseManager, instead of removing the masks that we ignore, we
now just filter for the masks we are interested in.
> Move XKeyGrabber out of KeyManager

- src/mousemanager.cpp
In the most recent commit 78a1e126, the MouseManager was changed to filter event modifiers to all supported modifiers instead of masking out a seperate list of modifiers. However, since Numlock is bound to Mod2 for most keymaps which was not masked out anymore, which means mousebinds (like the ones in the sample autostart) will only work if Numlock is off -- unless you define another mousebind including Mod2 for every action, so they work in both states.
This is just a small change to mask the locks out again, as before. It is not a big commit, but that change in behaviour feels unintended and this is probably the simplest way to have it behave in a more consistent way: It now behaves the same as key events again, where Numlock/Caps Lock are also masked out in case they are set as …
> Filter Numlock/Caps Lock modifiers out of mouse events to match key events

- tests/conftest.py
- tests/test_mousebind.py
Test that mouse bindings are independent of the numlock state. This adds
the test for the fix in #1490.
> Test mouse binds independent of numlock state

- MIGRATION
- NEWS
- doc/herbstluftwm.txt
- share/autostart
- src/framedecoration.cpp
- src/settings.cpp
- src/settings.h
- tests/conftest.py
- tests/test_decorations.py
- tests/test_doc.py
- tests/test_frame_decorations.py
- tests/test_settings.py
This new settings gives a more fine-grained control when frame decorations
are shown. The new setting strictly generalizes the always_show_frame
setting, which now only exists for backwards-compatibility.
The feature was requested in #1183, where it was reported that many
people find the initial frame decorations of a single big frame ugly
when starting hlwm for the first time. To address this, it maybe makes
sense to hide it per default. Thus, the setting is set to
`focused_if_multiple` in the in the default autostart.
Also, changing this default in settings.h should prevent new users
without an autostart from being confused by the red root frame (see
e.g. #599).
> New setting 'show_frame_decorations'

- tests/test_rules.py
On my setup (archlinux with gcc 12.1.0-2), the error message for
mismatched parentheses regular expressions has changed. This commit just
updates the error message in the test cases.
> Update regular expression parser error

- tests/conftest.py
The raw data of an image obtained from a screenshot depends on the
endianess. I couldn't make colormap.query_colors() work for depth 32 or
24, which would be the clean solution. Instead, we still parse the
binary image data manually and depend on the endianess of the system. In
principle, this could still be different from the image's endianess in
distributed X11 setups, but this should not happen when running the test
suite.
I could reproduce the issue #1486 on the ppc64 system gcc203 of the
gcc compile farm.
This fixes #1486.
> tests: Work around endianess in image data

- NEWS
- src/ipc-server.cpp
The Xlib function XChangeProperty() requires the data array to be
an array of 'long'. This causes wrong behaviour if long is larger than
int and if byte order is big-endian.
I could reproduce the issue #1414 on the ppc64 system gcc203 of the
gcc compile farm. Unfortunately, I don't see how I can verify the now
fixed issue in a test case.
There is another issue in the status property: the atom should have type
XA_CARDINAL instead of XA_ATOM. Changing this would require the
corresponding change in herbstclient. Strictly speaking, this would be
an incompatible change in the IPC protocol.
This fixes #1414.
> IPC Server: fix type of command status

- tests/test_meta_commands.py
Same change as in cce5f176 (#1497), in a different test case.
This fixes #1512.
> tests: Update another regex error message

- src/metacommands.cpp
The path is not used anyway, so it can be removed.
Thanks to @siccegge for reporting this.
> Remove unnecessary variable

- tests/conftest.py
- tests/test_autostart.py
- tests/test_ewmh.py
- tests/test_herbstclient.py
- tests/test_herbstluftwm.py
- tests/test_meta_commands.py
Before, running an ordinary hlwm.call() in a wait_stdout_match() context
consumed the token we were waiting for, making to context fail.
The present change fixes this by improves read_and_echo_output() to
support scanning for multiple tokens at the same time. This makes the
wait_stdout_match() contexts much easier to use.
> tests: Improve stdout/stderr synchronization

- src/css.cpp
- src/main.cpp
- tests/test_css.py
This makes the command name fit to the usual underscore-separated style
used in hlwm. Also, this turns the stylesheet parameter into an optional
flag `--stylesheet=...`.
> Rename debug-css to debug_css

- src/boxstyle.cpp
- src/boxstyle.h
- src/font.cpp
- src/font.h
- src/fontdata.cpp
- src/fontdata.h
- src/main.cpp
- src/widget.cpp
- src/x11-widgetrender.cpp
- tests/test_css.py
- tests/test_theme.py
- themes/separate-tabs.css
Introduce a new default value for fonts 'initial'. The value resolves to
an arbitrary font in the rare occassion that it is actually used for
rendering text. By this, we fix the following:
1. the empty string "" should not be a valid font description.
2. shared pointers of FontData objects (for "") should not be copied
all over the place when BoxStyles are inherited.
> Css: Only load font when needed

- MIGRATION
- NEWS
- src/panelmanager.cpp
- src/panelmanager.h
- src/signal.h
- tests/test_completion.py
- tests/test_panels.py
If a panel does not define _NET_WM_STRUT, we formerly just used it's window size for determining the reserved space at the screen edge. This caused issues such as #1475. By making it a setting, only those users who really need it can activate it.
While at it, I've fixed a bug in `Signal::connect()` arising from a wrong use of `std::bind()`.
This closes #1475 and #1175.
> Make geometry based panel detection an attribute

- src/settings.cpp
This just adds the so-far missing documentation of the value 'all' of settings.show_frame_decorations.
> Add missing doc for show_frame_decorations = all

- doc/herbstluftwm.txt
The 'shift' command has the same arguments as 'focus', so the doc also needs to be updated.
> Mention --level flag of the 'shift' command

- src/rulemanager.cpp
- src/rulemanager.h
- tests/test_rules.py
Previously, double hyphens were stripped in the tokenizeArg function which is only called after checking if the argument is "prepend", "once", "printlabel", "not", "!", or "fixedwidth". This failed to match on "--once", "--prepend", etc..., so the argument is eventually passed to tokenizeArg. But tokenizeArg expects all of its arguments to contain a = or ~ (everything else was supposed to be handled already). This resulted in an error.
Now, the stripping of hyphens is done at the beginning of rule parsing, and after manually moving the loop pointer for "not" and "!".
This closes #1487
> Re-enable using double hyphens before rule options

- src/css.cpp
- tests/conftest.py
- tests/test_completion.py
- tests/test_css.py
This fixes a crash of a nullptr dereference in debug_css if it is called with --print-tree but without a tree.
> Fix crash in debug_css

- tox.ini
In python-xlib 0.32, the bug https://github.com/python-xlib/python-xlib/pull/242 was introduced which caused `test_floatplacement_smart_create_many` to fail deterministically. There already is a pull request in `python-xlib` with a fix, but it is not merged yet. So for the time being, let's simply use the old python-xlib version.
> Stick to old python-xlib in CI until bugfix

- tests/test_keybind.py
The keysym 'Mode_switch' is irrelevant for one of the completion test, but makes it fail on newer X library versions. Thus, it is better to just disregard it in the test case.
This fixes #1560.
> Discard 'Mode_switch' from test about modifiers

- www/download.txt
The url schema for aur.archlinux.org has been changed.
> Update AUR package url

- src/framedecoration.cpp
- src/x11-utils.cpp
- src/x11-utils.h
This fixes incorrect rendering of resized, once-transparent focused frames with `frame_bg_transparent off`.
`window_make_intransparent` only took into account the _current_ size. Properly removing the mask allows for later resizing.
Fixes #1576.
> Restore non-transparent frame by removing mask

- tests/test_frame_decorations.py
This reproduces issue #1576 as a test case. The issue is that the frame background masks were not correctly reset; the issue was reported and fixed by @Storchschnabel.
Since the issue can be reproduced rather simply, this commit adds it as a test case.
> Reproduce issue #1576 as a test case

- .github/workflows/hlwm.yml
The `build-old-32bit` job failed because github has updated their base system but the job intentionally uses an old docker image:
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
```
The following suggestion might help for the time being: https://github.com/actions/checkout/issues/1590#issuecomment-2219382750
> CI: Allow old node version

- src/metacommands.cpp
In PR #1589, the test `test_foreach_clients` failed because `bool unique` was not initialized.
> Initialize bool argparse flags

- tests/test_layout.py
- tox.ini
This adds a new test case for the new values of the 'smart_window_surroundings' setting introduced in #1588.
Also, I've migrated of the existing test cases to new attribute getters/setters. By using the new geometry attributes of clients, I got rid of the x11 dependency in one of the existing test cases.
> Tests new 'smart_window_surroundings' options

- .github/workflows/hlwm.yml
It does not seem to be possible to let github actions pass data into old docker containers. So let us disable the old 32 bit build for the time being.
Also, this commit updates the version of the github action modules and installs imagemagick and librsvg2-bin in the website job to make the CI pass again.
> CI: remove old 32 bit job

- src/xconnection.cpp
With gcc 15, the C++ Standard Library no longer includes other headers that were internally used by the library. In herbstluftwm's case the missing header is `<stdint.h>`
Downstream Gentoo bug: https://bugs.gentoo.org/937529
Closes: #1612
> Add #include <stdint.h> to fix building with gcc 15

- tox.ini
- Use newline separated `passenv` values to [make things run with tox 4](https://tox.wiki/en/latest/upgrading.html#changed-ini-rules) (contrary to commas, newlines are backwards compatible with tox 3)
- Use `py3` without specifying a minor version, as the testsuite should work with ~any supported Python version, and it makes it easier to run it locally.
> tests: Modernize tox.ini
